### ISSUE TITLE
Update LiveViewNative Tutorial Prerequisites

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1005]
Working with @carson-katri today we discovered that Xcode 14.2 has issues running the LiveView Native Package due to missing types.

I think we should update the prerequisites for our tutorial to 14.3. Also, the Elixir version is pretty out of date too. I'm happy to update these if someone points me in the right direction :)

![image](https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/790c1067-27dc-4fc1-bdbf-10973e24e54e)

**Comment by BrooklinJazz** [comment]
14.2 causes the following type issues:

![image](https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/5e1e12e7-6170-4567-842e-8d69ff9cdd5f)

**Comment by AZholtkevych** [comment]
@carson-katri please check the PR and merge it
