### ISSUE TITLE
Collect the information about the environment and client version

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#1008]
As a PO, I'd like to have information about the environment and client version from iOS application. It should be shared with LiveView Native

**Comment by AZholtkevych** [comment]
More information available here: https://dockyard.slack.com/archives/C02E1GA5THB/p1689204260655069

**Comment by AZholtkevych** [comment]
Belongs to #993

**Comment by supernintendo** [comment]
Reading the convo referenced in this https://github.com/liveview-native/liveview-client-swiftui/issues/1008#issuecomment-1633339975 it looks like this was actually to ask for the environment and client version within the _GitHub issue form_ and not actually a change to the codebase. That was fixed [here](https://github.com/liveview-native/liveview-client-swiftui/pull/1108) so I think this can be closed.
