### ISSUE TITLE
Pattern/abstraction for caching data that originates from the server on the client

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#1013]
We have to have an established pattern or abstraction for caching data that originates from the server on the client, particularly for session tokens and the like? I know it’s possible to do this by messing about with the custom registry but I feel like its a common enough use case that we should have a solution for it.

**Comment by AZholtkevych** [comment]
Link to the discussion: https://dockyard.slack.com/team/U03GBMZ68JE

Entire discussion:

May Matyi
  [1:35 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690479323325449)
[@Carson Katri](https://dockyard.slack.com/team/U04FLNQF8P4)
 Do we have an established pattern or abstraction for caching data that originates from the server on the client, particularly for session tokens and the like? I know it’s possible to do this through messing about with the custom registry but I feel like its a common enough use case that we should have a solution for it.
[1:37](https://dockyard.slack.com/archives/C02E1GA5THB/p1690479466622379)
If possible, it would be nice if this could be handled by core so that its available for all platforms. I’m imagining an API that gets exposed via the platform’s FFI bridge that has put / get / delete methods for storing basic values like strings so that they’re available if you quit and relaunch the app.


bcardarella
  [3:10 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485007272889)
Anil did this for the original chat app and the TODO app
[3:10](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485022473839)
[@May Matyi](https://dockyard.slack.com/team/U03GBMZ68JE)
 I don't know if he established a pattern or just found a place to stash
[3:10](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485032289309)
but maybe the Registry should do this?


May Matyi
  [3:11 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485067746979)
Yeah, its possible with the custom registry but kind of a pain point IMO (edited) 
[3:11](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485096296609)
I think for such a common use case we should have a formal solution or an add on lib right?


bcardarella
  [3:11 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485101155799)
I agree we probably should have a pattern for this
[3:11](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485116668529)
but I defer to 
[@Carson Katri](https://dockyard.slack.com/team/U04FLNQF8P4)
 on the "how"


May Matyi
  [3:16 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485366857889)
I do think having an underlying representation of clientside state (i.e. in liveview-native-core) is worth considering though as this is something that every platform will need to figure out.


bcardarella
  [3:16 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485388305229)
yeah, even LiveView web allows for this
[3:16](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485411652309)
there are certainly things that don't make sense to have as a server state (edited) 
[3:17](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485467451859)
but what I wouldn't want is for people to just use LiveView Native as a api-less thing to send structured information over the wire for storage and client side handling
[3:17](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485470152429)
it's a fine line


May Matyi
  [3:18 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485531136189)
mhm, I think we should just start with primitive values like strings and ints; especially if we’re handling this in core to simplify the FFI path between Rust and whatever language the linked platform library is using


bcardarella
  [3:19 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485553976119)
yeah things like you're referring to for auth state I assume?


May Matyi
  [3:19 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485591595419)
correct, the main use case I have in mind is storing a session token so that when I close and open the app it preserves my login state


bcardarella
  [3:20 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485645297719)
yeah that's completely reasonable... if you are blocked by this I suggest just stashing somewhere you can get it for now and when Carson is back tomorrow we can chat about a better long-term API
:+1:
1

[3:20](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485658753909)
we should open an issue for this 
[@alex.zholtkevych](https://dockyard.slack.com/team/U04AHJJTRGC)


alex.zholtkevych
  [3:22 PM](https://dockyard.slack.com/archives/C02E1GA5THB/p1690485742908529)
On it

**Comment by AZholtkevych** [comment]
We have an issue in Core regarding that https://github.com/liveview-native/liveview-native-core/issues/37, but should we solve it here?

**Comment by matthieuchabert** [comment]
I came across the issue you're mentioning. If the user closes the app after being logged in, he will have to login again which is a non-ideal situation.

Do you have a pattern for this? I can't find any documentation about this issue.
Or how would I go with a custom registry? 

Thank you 🙏

**Comment by bcardarella** [comment]
@matthieuchabert nothing out of the box just yet but there is a workaround solution in the ElixirConf Chat app if you want to dig through there. @supernintendo can probably point out there is is happening.

In the future we are looking to add a `localStorage

**Comment by bcardarella** [comment]
Sorry I didn't mean to close

**Comment by matthieuchabert** [comment]
@bcardarella Thanks for your answer, I'll dig through the ElixirConf chat app.

Yes we're already using localStorage to restore some data when reconnecting a Liveview! Looking forward to your implementation with LiveView Native Core.

**Comment by bcardarella** [comment]
It might make sense for us to do this straight up in Swift for now so we can have the API there then refactor to use Core's when it is ready next year. I'll discuss with @carson-katri today to see if this is something we can add for v0.2. If it is a good amount of work I'll probably punt as I don't want to delay the v0.2 release

**Comment by carson-katri** [comment]
We can store data via cookies at the moment. But there is no built-in support for local storage yet.

**Comment by AZholtkevych** [comment]
Blocked by https://github.com/liveview-native/liveview-native-core/issues/37

**Comment by bcardarella** [comment]
We are now doing this in SwiftUI client and will have it implemented in Core
