### ISSUE TITLE
Could LiveViewCoordinator.pushEvent be more liberal with respect to the type of `event`?

### ISSUE THREAD

**Issue by stevegraham** [liveview-native/liveview-client-swiftui#1015]
`pushEvent` requires `JSONSerialization.isValidJSONObject` to be `true` with respect to `event`. Should it be possible that it accept data of types conforming to `Codable`?

**Comment by carson-katri** [comment]
Yeah, this should be possible and would be a nice usability improvement. I'll look into it.
