### ISSUE TITLE
Modifier -> SwiftUI Updated -> Model data: onChange(of:initial:_:) [BETA]

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#1053]
Doc: https://developer.apple.com/documentation/SwiftUI/View/onChange(of:initial:_:)-4psgg

**Comment by carson-katri** [comment]
We cannot support this modifier as it is for client-side state events.

**Comment by AZholtkevych** [comment]
Rejected
