### ISSUE TITLE
Button with phx-click doesn't seem to work within a NavigationLink

### ISSUE THREAD

**Issue by bryanj0410** [liveview-native/liveview-client-swiftui#1063]
I was going through the tutorial building the Cats app, I added the Button in the HStack to mark a cat as "favorite". This worked great until I added the NavigationLink to go to the detail view. Now you can't seem to click on the favorite Button, it will just do the navigation. Here is the render function:
```elixir
def render(%{platform_id: :swiftui} = assigns) do
    ~SWIFTUI"""
      <List modifiers={navigation_title(@native, title: "Cats!")}>
        <%= for {name, favorite} <- @cats_and_favorites do %>
          <NavigationLink id={name} destination={"/cats/#{name}"}>
            <HStack>
              <AsyncImage url={"/images/cats/#{name}.jpg"} modifiers={frame(@native, width: 100, height: 100)} />
              <Text><%= name %></Text>
              <Spacer />
              <Button phx-click="toggle-favorite" phx-value-name={name}>
                <Image system-name={if favorite, do: "star.fill", else: "star"} symbol-color={if favorite, do: "#f3c51a", else: "#000000"} />
              </Button>
            </HStack>
          </NavigationLink>
        <% end %>
      </List>
    """
  end
```

**Comment by AZholtkevych** [comment]
Rejecting according to the team

**Comment by bcardarella** [comment]
Can we include explanations as to why an issue is being rejected? Especially if someone from outside the team is opening the issue. Just rejecting without explanation is going to lead to people getting upset.

**Comment by carson-katri** [comment]
I provided an explanation for the issue and a workaround in a comment above. We are not using that tutorial anymore so it does not need to be updated.

> This matches the behavior of SwiftUI, which gives priority to the NavigationLink over the Button.

> use `highPriorityGesture`, a stack with the link and button separated, an overlay on the link, or some other method of giving the button priority
