### ISSUE TITLE
SwiftUI -> Layout Containers -> Layout transitions: ZStackLayout

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#107]
Doc: https://developer.apple.com/documentation/swiftui/zstacklayout

**Comment by AZholtkevych** [comment]
Moving to Q3 as discussed with @carson-katri

**Comment by AZholtkevych** [comment]
@shadowfacts please comment here an dI will reject this one

**Comment by shadowfacts** [comment]
We're not supporting the `Layout` protocol in templates, switching layouts can be accomplished by switching elements.
