### ISSUE TITLE
[Bug]: redirect inside handle_event/3 causes "Not Connected" issue on IOS

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1109]
### What happened?

redirect/2 navigation is not working inside of a handle event.

I've got a simple example that will reproduce the issue. I've defined the "/home" and the "/about" routes and have identical HomeLive and AboutLive liveviews.

```elixir
defmodule Mix4Web.HomeLive do
  use Mix4Web, :live_view
  use LiveViewNative.LiveView

  def mount(_params, _session, socket) do
    {:ok, redirect(socket, to: "/about")}
  end

  def render(%{platform_id: :web} = assigns) do
    ~H"""
    <.button phx-click="home">Home</.button>
    <.button phx-click="about">About</.button>
    """
  end

  def render(%{platform_id: :swiftui} = assigns) do
    ~SWIFTUI"""
    <Text>HOME</Text>
    <Button phx-click="home">Home</Button>
    <Button phx-click="about">About</Button>
    """
  end

  def handle_event("home", _params, socket) do
    {:noreply, redirect(socket, to: "/home")}
  end

  def handle_event("about", _params, socket) do
    {:noreply, redirect(socket, to: "/about")}
  end
end

```

Interestingly, navigation works fine when the redirect occurs in the `mount/3` callback, but not in the `handle_event/3` callback.

### Library Version

main

### XCode Version

14.3.1

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

IOS 16.4

**Comment by bcardarella** [comment]
@BrooklinJazz I believe you need to use `push_navigate`

`redirect` is intended for non-liveview apps. It will kill the socket and if you happen to redirect to another liveview route in the same app it will establish a new socket connection

**Comment by BrooklinJazz** [comment]
Thank you, I'll give that a go

**Comment by bcardarella** [comment]
Sorry, my note was incorrect. I believe `push_navigate` may stil be correct depending on your use-case but accoridng to the docs it will still shut down the socket https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#push_navigate/2

**Comment by BrooklinJazz** [comment]
Neither `redirect`, `push_patch`, or `push_navigate` appear to work for me.

**Comment by bcardarella** [comment]
I just want to confirm that these are liveview endpoints you're navigating to?

**Comment by BrooklinJazz** [comment]
Here's my router:

```elixir
  scope "/", Mix4Web do
    pipe_through :browser

    live "/", HomeLive
    live "/home", HomeLive
    live "/about", AboutLive
  end
```

And my handlers

```elixir
  def handle_event("home", _params, socket) do
    {:noreply, push_navigate(socket, to: "/home")}
  end

  def handle_event("about", _params, socket) do
    {:noreply, push_navigate(socket, to: "/about")}
  end
```

**Comment by BrooklinJazz** [comment]
is this reproducible, or only an issue on my machine?

**Comment by BrooklinJazz** [comment]
I can take 10-15 mins and set up a barebones project so other folks can see if it works for them.

**Comment by carson-katri** [comment]
Did you enable navigation in your Swift project?

**Comment by bcardarella** [comment]
@carson-katri is that something in our library? If so why wouldn't we have navigation enabled by default?

**Comment by carson-katri** [comment]
Yes, it’s part of the session configuration: https://liveview-native.github.io/liveview-client-swiftui/documentation/liveviewnative/livesessionconfiguration/navigationmode-swift.property

I’m not sure what the reasoning behind `disabled` being default was. I think the navigation mode API was added before I joined the project.

**Comment by bcardarella** [comment]
navigation shouldn't even be an option, it should just be always on. @carson-katri I'm going to create an issue to remove the configuration option entirely

**Comment by bcardarella** [comment]
@carson-katri are there any more opt-into configurations? Applications should be fully functional without any flipping of switches. If there are other options like navigation we need to remove those make them always on.

**Comment by BrooklinJazz** [comment]
Sorry for the tardy response @carson-katri. I had wondered if that was the issue, because I noticed the config option in the Navigation tutorial, but thought perhaps it was only for the NavigationLink component.

I'll try to add it in to confirm if that's the problem but I do agree with Brian here that it would be nice if it wasn't necessary.

**Comment by BrooklinJazz** [comment]
Hmm, @carson-katri I'm not sure I'm configuring it correctly. The navigation is being triggered but I still get a "Not Connected" issue. Here's my `ContentView`.

```elixir
import SwiftUI
import LiveViewNative

struct ContentView: View {
    @StateObject private var session: LiveSessionCoordinator<EmptyRegistry> = {
        var config = LiveSessionConfiguration()
        config.navigationMode = .enabled
        return LiveSessionCoordinator(URL(string: "http://localhost:4000/")!, config: config)
    }()
    
    var body: some View {
        LiveView(session: session)
    }
}
```

**Comment by BrooklinJazz** [comment]
https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/2a41906d-9134-431c-b453-00e22799e606

**Comment by BrooklinJazz** [comment]
Adding the issue #1110 to this convo for tracking purposes.

**Comment by cohawk** [comment]
I've had a couple bumps in the road with Navigation and @BrooklinJazz - I have been able to reproduce your "Not Connected" issue, but I am not sure _exactly_ what solved it.

Do you have any other `scope "/", Mix4Web` in your router?  Possibly Authentication routes?

For example with this router setup I get the "Not Connected" error on the `/users/register` & `/users/log_in` routes:
router.ex
```elixir
  scope "/", RealmsWeb do
    pipe_through :browser

    live "/", HomeLive, :index
    live "/counter", CounterLive, :index
  end

  ## Authentication routes

  scope "/", RealmsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    # get "/", PageController, :home

    live_session :redirect_if_user_is_authenticated,
      on_mount: [{RealmsWeb.UserAuth, :redirect_if_user_is_authenticated}] do
      live "/users/register", UserRegistrationLive, :new
      live "/users/log_in", UserLoginLive, :new
      live "/users/reset_password", UserForgotPasswordLive, :new
      live "/users/reset_password/:token", UserResetPasswordLive, :edit
    end

    post "/users/log_in", UserSessionController, :create
  end
```

But moving all the routes under the `live_session` scope the Navigation works without the "Not Connected" error, so maybe has something to do with multiple scopes?  I cannot figure it out
```elixir
  scope "/", RealmsWeb do
    pipe_through :browser
  end

  ## Authentication routes

  scope "/", RealmsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    # get "/", PageController, :home

    live_session :redirect_if_user_is_authenticated,
      on_mount: [{RealmsWeb.UserAuth, :redirect_if_user_is_authenticated}] do
      live "/", HomeLive, :index
      live "/counter", CounterLive, :index
      live "/users/register", UserRegistrationLive, :new
      live "/users/log_in", UserLoginLive, :new
      live "/users/reset_password", UserForgotPasswordLive, :new
      live "/users/reset_password/:token", UserResetPasswordLive, :edit
    end

    post "/users/log_in", UserSessionController, :create
  end
```

**Comment by BrooklinJazz** [comment]
Interesting. I have a pretty simple router:

```elixir
  scope "/", Mix4Web do
    pipe_through :browser

    live "/", MenuLive
    live "/game/:game_id", GameLive
  end
```

I tried putting them in a live_session, but the issue persists.

```elixir
scope "/", Mix4Web do
  pipe_through :browser

  live_session :mix4 do
    live "/", MenuLive
    live "/game/:game_id", GameLive
  end
end
```

**Comment by carson-katri** [comment]
@BrooklinJazz could you provide the commit that your app is depending on, or run `Packages` > `Update to Latest Package Versions`? I'd like to ensure you have the latest navigation fixes made in #1019, #1055, and #1081

**Comment by BrooklinJazz** [comment]
After updating packages I was able to reproduce the issue on @ivanhoe's machine.

**Comment by carson-katri** [comment]
@BrooklinJazz Are you using `push_navigate`?

**Comment by BrooklinJazz** [comment]
Yup, I also reproduced this after updating packages on my machine. Ivan was using Swiftui NavigationLink components, I'm using `push_navigate`. I also tried `push_patch` and `redirect`. All had the "Not connected" issue.

**Comment by BrooklinJazz** [comment]
We fixed the handle_event/3 issue (or it was already fixed and I updated packages)

However, there's still an issue with handle_info. @carson-katri and I narrowed this down to: handle_info/3 will not navigate when we call push_navigate.
