### ISSUE TITLE
Modifiers do not match SwiftUI spec.

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1111]
## Intro

Our `background` modifier doesn't match the SwiftUI documentation. I'm bringing this specific issue up to start a larger conversation around modifiers and our overall documentation of LVN.

## Background Modifier Example

Here's how to use the modifier in an LVN app:

```elixir
<VStack modifiers={@native |> background({:color, :red})}>
  <Text>Hello World</Text>
</VStack>
```

Here's how to use it in a SwiftUI app.

```elixir
var body: some View {
    VStack {
        Text("Hello, World!")
    }
    .background(Color.purple)
}
```

Here's how it's documented on our docs: https://liveview-native.github.io/liveview-client-swiftui/documentation/liveviewnative/backgroundmodifier

```swiftui
<HStack>
  <Image system-name="heart.fill" modifiers={@native |> background(alignment: :center, content: :bg_content)}>
    <Circle template={:bg_content} />
  </Image>
</HStack>
```

Here's the module: https://hexdocs.pm/live_view_native_swift_ui/LiveViewNativeSwiftUi.Modifiers.Background.html

```elixir
defmodule LiveViewNativeSwiftUi.Modifiers.Background do
  use LiveViewNativePlatform.Modifier

  alias LiveViewNativeSwiftUi.Types.{KeyName, ShapeStyle, Shape, EdgeSet, FillStyle}

  modifier_schema "background" do
    field :alignment, Ecto.Enum, values: ~w(
      bottom
      bottom_leading
      bottom_trailing
      center
      leading
      leading_last_text_baseline
      top
      top_leading
      top_trailing
      trailing
      trailing_first_text_baseline
    )a
    field :content, KeyName
    field :style, ShapeStyle
    field :shape, Shape
    field :ignores_safe_area_edges, EdgeSet
    field :fill_style, FillStyle
  end

  def params({type, _} = style, [in: shape, fill_style: fill_style]) when is_atom(type) and not is_boolean(type) and not is_nil(type), do: [style: style, shape: shape, fill_style: fill_style]
  def params({type, _} = style, [in: shape]) when is_atom(type) and not is_boolean(type) and not is_nil(type), do: [style: style, shape: shape]
  def params({type, _} = style, [ignores_safe_area_edges: edges]) when is_atom(type) and not is_boolean(type) and not is_nil(type), do: [style: style, ignores_safe_area_edges: edges]
  def params([in: shape, fill_style: fill_style]), do: [shape: shape, fill_style: fill_style]
  def params([in: shape]), do: [shape: shape]
  def params({type, _} = style) when is_atom(type) and not is_boolean(type) and not is_nil(type), do: [style: style]
  def params(params), do: params
end
```

## Suggestion

When I last brought this up @bcardarella said our intent is to lean on the Apple documentation and keep the naming of modifiers 1:1 to avoid recreating the Apple docs.

However, I'm generally finding it difficult to translate their documentation into our syntax. Here's the Apple documentation for the `background` modifier: https://developer.apple.com/documentation/swiftui/view/background(alignment:content:) It doesn't seem to provide enough information to determine the correct syntax.

I'd like to understand how we can better document LVN and how I can help the team. While this may conflict with Brian's desire above, what about focusing on the LVN hexdocs https://hexdocs.pm/live_view_native_swift_ui/LiveViewNativeSwiftUi.Modifiers.Background.html as our single source of truth since that's where most of the Elixir community likely would go first to understand the library?

If that doesn't work, then how can we improve our documentation and the overall onboarding experience for LVN?

**Comment by BrooklinJazz** [comment]
I'll post any modifiers I find that don't seem to match the SwiftUI spec.

### cornerRadius

Apple Docs:

```swiftui
Text("Round Me")
    .cornerRadius(15)
```

Actual:

```elixir
<Text modifiers={corner_radius(radius: 10)} id="board">Round Me<Text>
```

Expected:

```elixir
<Text modifiers={corner_radius(10)} id="board">Round Me<Text>
```

**Comment by BrooklinJazz** [comment]
The `frame` modifier does not have the ability to handle `:infinity` as I would expect. It seems like the current workaround is to use a large number such as `9999`.

SwiftUI Version:

```js
Text("Full Width Frame")
    .frame(maxWidth: .infinity)
```

Actual:

```elixir
<Text modifiers={frame(max_width: 9999)}>Full Width Frame</Text>
```

Expected:

```elixir
<Text modifiers={frame(max_width: :infinity)}>Full Width Frame</Text>
```

**Comment by BrooklinJazz** [comment]
## Font

SwiftUI:

```elixir
Text("Title")
        .font(.title)
```

Actual:

```elixir
<Text modifiers={font(font: {:system, :title})}>Title</Text>
```

Expected:

```elixir
<Text modifiers={font(:title)}>Title</Text>
```

**Comment by carson-katri** [comment]
* `background` - can you provide an example case where it doesn't match SwiftUI? From what I can tell the syntax is equivalent.
* `frame` - Swift's `Double` type has an [`infinity`](https://developer.apple.com/documentation/swift/double/infinity) static member, so this is not a feature of SwiftUI but instead just another number value. From what I can tell, Elixir does not have an equivalent so you need to just provide a large number.
* `font` and `corner_radius` - we need to add a `params` function to hide the `font: ...` argument label. I can look into adding these for any modifiers that are missing it.

**Comment by BrooklinJazz** [comment]
> background - can you provide an example case where it doesn't match SwiftUI? From what I can tell the syntax is equivalent.

The difficulty is that SwiftUI uses `Color.red` but it's not clear to me that should be translated to `{:color, :red}` or how I could have found that information without referring to our example project (which is more digging than the typical dev will want to do).

```elixir
<VStack modifiers={@native |> background({:color, :red})}>
  <Text>Hello World</Text>
</VStack>
```

> frame - Swift's Double type has an [infinity](https://developer.apple.com/documentation/swift/double/infinity) static member, so this is not a feature of SwiftUI but instead just another number value. From what I can tell, Elixir does not have an equivalent so you need to just provide a large number.

Don't we have control over the `params` function inside of the modifier? Couldn't we hide this translation by pattern matching on an `:infinity` atom? Something like:

```elixir
# frame.ex
 def params(width: :infinity), do: [width: 9999]
```

I know this would be a little more complex since there are multiple fields, just showing an example of how we could handle it.
