### ISSUE TITLE
Can we set the background color for a view, rather than as a modifier on its children?

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1112]
### Setting Background Color

Do we have the ability to set the color for an entire view (including the frame)? I'm not sure how to accomplish it with modifiers. It seems like it's an "Attribute" but I'm a bit fuzzy with my understanding of how Attributes work.

Here's an example taken from: https://www.hackingwithswift.com/books/ios-swiftui/colors-and-frames
<img width="858" alt="image" src="https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/bd98ddea-ba92-4573-90d6-e3eab76bb213">

**Comment by carson-katri** [comment]
I'm not sure I entirely understand the problem. The template for those examples would be something like this:

```heex
<ZStack>
  <Text modifiers={background({:color, :red})}>Your content</Text>
</ZStack>
```

```heex
<ZStack>
  <Color name="system-red" />
  <Text>Your content</Text>
</ZStack>
```

When you place a `background` modifier on a `View`, it gives the background content the entire frame of the View to work with. So if you adjust the frame with a frame modifier (which must come before the background) it will be given that space as well.

`Color` can also be used as an element, in which case it draws a rectangle that fills the available space.

**Comment by BrooklinJazz** [comment]
> When you place a background modifier on a View, it gives the background content the entire frame of the View to work with. So if you adjust the frame with a frame modifier (which must come before the background) it will be given that space as well.

Ah, so the reason it doesn't apply to the entire frame of the <Text> element is because it's not a View. But If I use a View, then it will apply to the entire frame? roger.

> Color can also be used as an element, in which case it draws a rectangle that fills the available space.

Using `Color` as an Element also solves my problem. Thank you!

Closing this issue.

**Comment by carson-katri** [comment]
Everything is a `View`, but the way SwiftUI layout works is:
1. The parent proposes a size to the child.
2. The child chooses its size. It can use as much of the proposed space as it wants, or even choose a bigger size than it was proposed.
3. The parent positions the child wherever it wants.

So in this case:
1. `background` modifier (technically a View under the hood) proposes the exact size of the `Text` to the background content.
2. The background content (essentially a red rectangle) is flexible, so it will use up all of the proposed space (which does not extend beyond the `Text`)
3. The `background` modifier centers the child behind the text.

If you put a frame with a very large max width/max height *before* the background, it will create a container around the `Text` that uses all of the space proposed to the `Text` content (perhaps the entire screen if at the root of the app). Then the background will be proposed the size of this frame container.

In the second case, it works differently:
1. The root of the app proposes the entire screen to the `ZStack`.
    1. The `ZStack` proposes the entire screen to the red rectangle
    2. The red rectangles accepts the entire screen as its size.
    3. The `ZStack` proposes the entire screen to the `Text`
    5. The `Text` only wants its exact rendered size.
    6. The `ZStack` centers the red rectangle and `Text`
2. The `ZStack` chooses its size to be the size of the largest element it contains (the rectangle)
3. The root of the app places the `ZStack` in the center.

SwiftUI layout is very different than web layout, and I've spent a lot of time reverse engineering and re-implementing its behavior 😅
