### ISSUE TITLE
Unable to set `resizable` modifier on Image

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1113]
> Note: Apologies if I'm pinging the issue tracker too much! I'm not trying to be a bother, just mentioning issues as I encounter them so we can be prepared for Elixir Conf coming up. I appreciate how amazing the LVN team is and how supportive you've been of my recent exploration into the library!

Now for my current issue, It seems like the `resizable` modifier isn't applying to my Image.

I'm trying to reproduce the following swiftui code in LVN.

```javascript
Image("myImage")
            .resizable()
            .scaledToFit()
            .frame(width: 200, height: 200)
```

Which I've confirmed works in the simulator:

<img width="955" alt="image" src="https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/f756f33c-9ff7-465b-bd33-279c42f027c7">

Here's my render.

```elixir
  def render(%{platform_id: :swiftui} = assigns) do
    ~SWIFTUI"""
    <Image
      system-name="drop.fill"
      modifiers={
        foreground_color(:purple)
        |> resizable([])
        |> scaled_to_fit([])
        |> frame(width: 200, height: 200)
      }
    />
    """
  end
```

Yet it produces the following:

![image](https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/a9bcd544-590a-4c78-8011-595c692c2834)

Am I doing something incorrectly, or are the `resizable` and `scaled_to_fit` modifiers not working as expected?

**Comment by carson-katri** [comment]
Image-specific modifiers like `resizable` need to go first in the modifier stack, so this might work:
```heex
<Image
  system-name="drop.fill"
  modifiers={
    resizable([])
    |> scaled_to_fit([])
    |> foreground_color(:purple)
    |> frame(width: 200, height: 200)
  }
/>
```

**Comment by BrooklinJazz** [comment]
I'll give this a try as soon as I'm free

**Comment by BrooklinJazz** [comment]
This resolved my issue
