### ISSUE TITLE
LiveViewCoordinator access (pushEvent)

### ISSUE THREAD

**Issue by stevegraham** [liveview-native/liveview-client-swiftui#1123]
This is a continuation of #1014, which adds the ability to receive events on a LiveSessionCoordinator but unfortunately there is still no way to push events.

Use case:

I have a SwiftUI view that combines LVN with some native interop. Specifically a native component provides a token via callback that I want to push to the server, which will then use it to make API requests on behalf of the user to retrieve resources owned by the user on the 3rd party API service.

```swift
import SwiftUI
import LiveViewNative
import Teller

struct ContentView: View {
    let userId: String
    @State var presentTellerConnect: Bool
    @StateObject var coordinator: LiveSessionCoordinator<EmptyRegistry>
    
    init(userId: String) {
        self.userId = userId
        self.presentTellerConnect = false
        
        var config = LiveSessionConfiguration()
        config.navigationMode = .enabled
        var coordinator = LiveSessionCoordinator(URL(string: "http://127.0.0.1:4000/accounts?token=\(userId)")!, config: config)
        self._coordinator = StateObject(wrappedValue: coordinator)
    }
    
    var body: some View {
        LiveView(session: coordinator)
            .onAppear {
                Task.init {
                    coordinator.handleEvent("present-tc", handler: { (_, payload) in
                        presentTellerConnect = true
                    })
                }
            }
            .tellerConnect(isPresented: $presentTellerConnect, config: TellerConnect.Config(
                appId: "app_oj5u9c4lklkm6epl1s000",
                environment: .sandbox,
                selectAccount: .multiple,
                completion: { event in
                    switch event {
                    case .enrollment(let authorization):
                        Task.init {
                            // I want to do a pushEvent here
                        }
                    default:
                        break
                    }
                }
            )
        )
    }
}
```

I thought about creating a view that inherits from LiveView, but rootCoordinator is private.

I'm either looking for guidance on what you think is the correct way to do this within the current API, or for pushEvent to be made available on `LiveSessionCoordinator`.

**Comment by stevegraham** [comment]
My current workaround is to force overwrite `LiveSessionCoordinator` in my local copy with the following two delegate functions:

```swift
public class LiveSessionCoordinator<R: RootRegistry>: ObservableObject {
    // ...
    
    var rootCoordinator: LiveViewCoordinator<R>!

    public func pushEvent(type: String, event: String, value: Any, target: Int? = nil) async throws {
        try await rootCoordinator.pushEvent(type: type, event: event, value: value, target: target)
    }
    
    // Delegate function for pushing events (for some Encodable type)
    public func pushEvent(type: String, event: String, value: some Encodable, target: Int? = nil) async throws {
        try await rootCoordinator.pushEvent(type: type, event: event, value: value, target: target)
    }

    // ...
}
```

I don't know what you think the correct solution is though.

**Comment by carson-katri** [comment]
Depending on the configured `navigationMode`, `rootCoordinator` may not be the presented one. A better option may be to do something like `navigationPath.last?.coordinator ?? rootCoordinator`. This will ensure you always send an event to the top-most LiveView in the navigation stack.

Another option would be to expand the `LiveSessionCoordinator` to have a property similar to [`presentedViewController`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621407-presentedviewcontroller) in UIKit. Something like `presentedLiveViewCoordinator`, which would do that lookup automatically.
