### ISSUE TITLE
Preserve previous document while reconnecting

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-swiftui#1130]
When the app reconnects (such as during navigation or when returning from the background), the loading state is always displayed. For a more seamless experience, the previous document could stay presented and re-hydrate when the connection is re-established.

One thing to make it more clear that the app is loading could be adding `disabled` around the entire hierarchy during this loading process. This would ensure that the user cannot interact with the app while the connection is dead.

**Comment by AZholtkevych** [comment]
@simlay and @carson-katri could you please review this together
