### ISSUE TITLE
Add support for class names to custom registry

### ISSUE THREAD

**Issue by supernintendo** [liveview-native/liveview-client-swiftui#1133]
We would like the custom registry to allow clientside handling of modifiers by providing a way to map view modifiers to class names. This will allow add-on libraries to provide custom styles and build an escape hatch from serverside-only modifiers while we work out design and performance issues with the current implementation (see https://github.com/liveview-native/liveview-client-swiftui/issues/1132).

**Comment by AZholtkevych** [comment]
On Hold for now. We have a doubts to proceed with that

**Comment by AZholtkevych** [comment]
We won't be proceeding with that one
