### ISSUE TITLE
Swift Playgrounds Install Failure

### ISSUE THREAD

**Issue by KhaledPendleton** [liveview-native/liveview-client-swiftui#1135]
### What happened?

`Could not resolve package graph` error received when attempting to install package in Swift Playgrounds, on iPad Pro, running iPadOS 17.
![Swift package manager error popup](https://elixirforum.com/uploads/default/original/3X/5/e/5ec27d64724ca3b8fb5821c7c2cf8bff56d388c8.jpeg)

### Library Version

0.1.1

### Xcode Version

Swift Playgrounds

### Swift Version

5.8

### On which device or simulator are you running into the problem?

iPhone, iPad

### Target Device Operating System Version

iPadOS

### Relevant log output

```shell
Could not resolve package graph. Cannot continue.
failed validating archive from 'https://github.com/liveview-native/liveview-native-core/releases/
download/0.1.0-7500c9/liveview_native_core.xcframework.zip' which is required by binary target
"liveview _native_core': could not find executable for 'unzip
```

**Comment by KhaledPendleton** [comment]
[Previous discussion](https://elixirforum.com/t/liveview-native-client-install-failure-swift-playgrounds/58454)

**Comment by carson-katri** [comment]
I was able to get a more descriptive error by creating a Playground App in Xcode:

> This Swift Playgrounds project depends on a binary library, and will therefore not be buildable in Swift Playgrounds.

This binary library is `liveview-native-core` (the shared part of LiveView Native implemented in Rust), which is required for LiveView Native to function. Unfortunately, support for this needs to be added to Swift Playgrounds by Apple. From what I can find, Swift Playgrounds apps can only use pure-Swift packages.
