### ISSUE TITLE
[Bug]: Fresh app fails to build due to unsafe build flags

### ISSUE THREAD

**Issue by noozo** [liveview-native/liveview-client-swiftui#1136]
### What happened?

![image](https://github.com/liveview-native/liveview-client-swiftui/assets/3353/f7f919bc-bc14-4852-bba0-ce8d6f1c8aa1)

### Library Version

0.1.1

### Xcode Version

15.0

### Swift Version

5

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

iOS 17.0

**Comment by carson-katri** [comment]
Odd that we didn’t run into that with previous versions. We have some flags for documentation that can be removed, and a new patch tagged.

**Comment by noozo** [comment]
i read somewhere that previous xcode versions did not check unsafe build flags properly, so it might have started now with the new version.

**Comment by noozo** [comment]
Noteworthy: When running an app generated by `mix lvn.install` this problem does **not** occur, only when creating a new project and adding the dependency manually via swift PM.

**Comment by noozo** [comment]
also, ran the generator and then added this to my index live view:
```
@impl true
  def render(%{platform_id: :swiftui} = assigns) do
    ~SWIFTUI"""
    <VStack>
      <Text phx-click="bla">
        Hello Native iOS Passionfruit
      </Text>
    </VStack>
    """
  end
  ```
  
as well as `use LiveViewNative.LiveView`.

The app does connect to the channel, and gets the markup back, but nothing is rendered (blank simulator as in pic)

![image](https://github.com/liveview-native/liveview-client-swiftui/assets/3353/84662d5f-030d-4a48-9093-00b71717c623)

**Comment by noozo** [comment]
![image](https://github.com/liveview-native/liveview-client-swiftui/assets/3353/035bf529-955c-4cbd-9b7e-63e54e312fb1)

**Comment by noozo** [comment]
i found out why. A big caveat: If existing live views use a layout, LVN renders blank: 
```
use Phoenix.LiveView, layout: {MyAppWeb.LayoutView, :live}
```
if i comment out the layout option it works.

**Comment by bcardarella** [comment]
@noozo yes, this is a known issue and we're collaborating with the Phoenix core team on fixing this. The tldr; is that LiveView doesn't respect `format` the same way the dead view rendering will. So we cannoy easily implement non-html formatted layouts and with using `use MyAppWeb, :liveview` will kill the app as the LVN clients don't know what to do with HTML elements.
