### ISSUE TITLE
Unrecognized views and modifiers shouldn't crash the client

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1140]
Currently if any HTML somehow makes its way into the document (i.e. layouts) the client will crash. What we should do instead:

1. if the client encounters a view who's name isn't registered then we ignore that view. We also should not go down that view's branch if it has children.
2. in `dev` mode we should log out all relevant informtaion about the unrecognized view name

We should also support a similar behavior for unrecognized modifiers:

1. if the client encounters a modifier name that isn't registered then we ignore that modifiers. If there is a type mismatch with any of the arguments passed to the modifier we ignore that modifier. In both cases we continue on to applying the the next modifiers.
2. Our proposal has an AST as `{<identifier>, <annotations>, <arguments>}`. While it hasn't yet been spec'd out the `<annotations>` element of the tuple will include some source information on the modifier. We will likely include the path name of the file and the LOC the modifier is used on. This will allow us to provide some logging information in `dev` mode something like this:

> Tried to apply `w-82` class to view `Text`. Modifier `colors(color: .red)` doesn't exist
> path: "lib/my_app_web/stylesheets/swiftui.sheet:87"

In the event no annotation information is provided we should probably just do our best to print out the original AST

**Comment by carson-katri** [comment]
The client doesn't crash if it encounters an unknown View. It just doesn't render anything as you describe in 1.

https://github.com/liveview-native/liveview-client-swiftui/blob/0e0fc6bbe5e95ef308e51551af0889acb09b87b3/Sources/BuiltinRegistryGenerator/BuiltinRegistryGenerator.swift#L86-L88

There are no logs, so that could be improved.

**Comment by bcardarella** [comment]
@carson-katri ah ok, and because the SwiftUI views are children of that parent HTML element it ignores the branch?

**Comment by carson-katri** [comment]
Yes, exactly. It stops at the parent.
