### ISSUE TITLE
[Bug]: No Connection

### ISSUE THREAD

**Issue by matthieuchabert** [liveview-native/liveview-client-swiftui#1165]
### What happened?

The simulator displays a **No Connection** placeholder even though the server sends the correct response.

I proxy my Phoenix local server through Ngrok, because we force the use of https and Xcode doesn't allow self-signed ssl certificates. 

Here's the response proxied through Ngrok:

```html
<div data-phx-main data-phx-session="SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY1UEhIRkF6RkRUb01kOEV3B3Nlc3Npb250AAAAAHcKcGFyZW50X3BpZHcDbmlsdwZyb3V0ZXJ3FkVsaXhpci5NYXJrb1dlYi5Sb3V0ZXJ3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggAnKHih4nDkxd3BHZpZXd3GkVsaXhpci5NYXJrb1dlYi5Nb2JpbGVMaXZldwlyb290X3ZpZXd3GkVsaXhpci5NYXJrb1dlYi5Nb2JpbGVMaXZldwhyb290X3BpZHcDbmlsbgYAIyeMj4sBYgABUYA.MJXYVxO78uHOP7z79BPD_UDrHhLB0MKxf1r-LDUTITA" data-phx-static="SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY1UEhIRkF6RkRUb01kOEV3CmFzc2lnbl9uZXdqdwVmbGFzaHQAAAAAbgYAIyeMj4sBYgABUYA.euipFKGqgGxV-aZDJOU40q9pXkDSjiqKl40PCZbjWCk" id="phx-F5PHHFAzFDToMd8E"><VStack>
  <Text>
    Hello native!
  </Text>
</VStack></div> 
```

And the Swift part:

```swift
struct ContentView: View {
    @StateObject private var session = LiveSessionCoordinator(URL(string: "https://f4a2-45-201-193-244.ngrok-free.app/mobile")!)
    
    var body: some View {
        LiveView(session: session)
        }
}
```

Am I missing some configuration somewhere?

### Library Version

main

### Xcode Version

15.0.1

### Swift Version

5

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

iOS 17

### Relevant log output

```shell
Connecting to https://f4a2-45-201-193-244.ngrok-free.app/mobile/
```

**Comment by carson-katri** [comment]
Did you [configure ATS](https://developer.apple.com/documentation/security/preventing_insecure_network_connections) for your app in Xcode?

In `Info.plist` add a new key `App Transport Security Settings`. Within that dictionary, add another key `Allow Arbitrary Loads` and set it to `YES`. You can alternatively add an exception for individual domains.

![3138689~dark@2x](https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/18d56034-7db0-4a59-9d54-37f464f94b16)

If your app doesn't have a separate `Info.plist` file, you can configure this by selecting the Xcode project in the sidebar, choosing your app target in the nested sidebar, and selecting the `Info` tab at the top. Then you can edit the "Custom iOS Target Properties".

<img width="958" alt="Screenshot 2023-11-02 at 10 41 48 AM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/46471c50-870d-46c2-b412-18263ee6cab2">

**Comment by bcardarella** [comment]
@BrooklinJazz can you track this for people that are using ngrok over SSL?

**Comment by matthieuchabert** [comment]
Thanks for your answer. Yes I did previously, but I don't think it's related as Ngrok forwards a secure connection, for example: `https://f4a2-45-201-193-244.ngrok-free.app`

![CleanShot 2023-11-02 at 15 55 31@2x](https://github.com/liveview-native/liveview-client-swiftui/assets/32734509/fb90be30-3205-4728-9c7e-95d8bedbcd88)

**Comment by bcardarella** [comment]
...I jumped the gun there. @BrooklinJazz once we figure out the problem, track that solution 😄

**Comment by matthieuchabert** [comment]
@carson-katri There's only one line.. 

![CleanShot 2023-11-02 at 16 14 26@2x](https://github.com/liveview-native/liveview-client-swiftui/assets/32734509/4f7f0265-5e3a-4ac2-a27f-310c431fe852)

Do I have to set a variable in the ATS to get more logs?

**Comment by matthieuchabert** [comment]
here's the console output for this breakpoint:

![CleanShot 2023-11-02 at 16 48 31@2x](https://github.com/liveview-native/liveview-client-swiftui/assets/32734509/d85e3edc-fbc0-4c66-9c62-891d1b2ce72d)


```html
<div data-phx-main data-phx-session=\"SFMyNTY.g2gDaAJhBXQAAAAIdwJpZG0AAAAUcGh4LUY1UFk5ZG45RG1ma0lweGx3B3Nlc3Npb250AAAAAHcKcGFyZW50X3BpZHcDbmlsdwZyb3V0ZXJ3FkVsaXhpci5NYXJrb1dlYi5Sb3V0ZXJ3DGxpdmVfc2Vzc2lvbmgCdwdkZWZhdWx0bggAnKHih4nDkxd3BHZpZXd3GkVsaXhpci5NYXJrb1dlYi5Nb2JpbGVMaXZldwlyb290X3ZpZXd3GkVsaXhpci5NYXJrb1dlYi5Nb2JpbGVMaXZldwhyb290X3BpZHcDbmlsbgYARJ-3kIsBYgABUYA.9xVoGA7TqFE92BDROacntzxs2uTmSEmK5l169bfjey0\" data-phx-static=\"SFMyNTY.g2gDaAJhBXQAAAADdwJpZG0AAAAUcGh4LUY1UFk5ZG45RG1ma0lweGx3CmFzc2lnbl9uZXdqdwVmbGFzaHQAAAAAbgYARJ-3kIsBYgABUYA.1RADG0hTWFP_cK78IWDC2diEuInt0q52kdu4N2EzIhs\" id=\"phx-F5PY9dn9DmfkIpxl\"><VStack>\n  <Text>\n    Hello native!\n  </Text>\n</VStack></div>
```

**Comment by carson-katri** [comment]
I think you also need to have a `<meta name="csrf-token">` somewhere for it to connect the socket correctly.

```html
<head>
  <meta name="csrf-token" content={csrf_token_value()}>
</head>
```

**Comment by matthieuchabert** [comment]
That solved the issue thanks a lot ❤️

I was missing the root layout with a few meta attributes. I don't know why I thought I had to remove the layout and only send the body of the html response..

**Comment by bcardarella** [comment]
@matthieuchabert fwiw the layout is only required in the first dead render. We first fetch that and extract the connection information then establish the LV connection. There will be some changes to this coming in the near future that hopefully these issues won't pop up any longer.
