### ISSUE TITLE
[Bug]: The TextField sends a "text" key but other controls send a "value" key.

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1178]
### What happened?

I'm not sure if this is a bug.

However, the `phx-change` event binding sends `params` as `%{"value" => value}` for every other control view I have tried other than the `TextField`. For a `TextField` the `params` are sent as `%{"text" => value}`.

Is this desirable?

### Library Version

main

### Xcode Version

15

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

IOS 17

**Comment by carson-katri** [comment]
The value matches the attribute used to set it. Controls like `Slider`, `Stepper`, etc. use `value`. `TextField` uses the `text` attribute. `Picker`, `DatePicker`, etc. use `selection`.

It is based on the name of the `Binding` argument of the Views initializer in SwiftUI: https://developer.apple.com/documentation/swiftui/textfield/init(_:text:)-4lffk

**Comment by BrooklinJazz** [comment]
That makes sense. I'll include that in the description. Feel free to close.
