### ISSUE TITLE
[Bug]: Archiving a new project based on the lvn.install generator fails

### ISSUE THREAD

**Issue by pshoukry** [liveview-native/liveview-client-swiftui#1183]
### What happened?

When trying to archive a newly generated project it fails with error: Command PhaseScriptExecution failed with a nonzero exit code
dyld[63263]: Library not loaded: @rpath/ArgumentParser_39B7DAEE4DD359BE_PackageProduct.framework/Versions/A/ArgumentParser_39B7DAEE4DD359BE_PackageProduct
  Referenced from: <33696BAF-384D-3954-8DA9-352290975FFD> /Users/User/Library/Developer/Xcode/DerivedData/Split-cdoycibfxsrespfmeafgxtkoxnjq/Build/Intermediates.noindex/ArchiveIntermediates/Split/IntermediateBuildFilesPath/UninstalledProducts/macosx/BuiltinRegistryGenerator
  Reason: no LC_RPATH's found

### Library Version

latest

### Xcode Version

15

### Swift Version

swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1) Target: arm64-apple-macosx14.0

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

Mac 14.1.2 (23B92)

**Comment by pshoukry** [comment]
This is now happening when I try to archive any project with live view native.

Steps to reproduce:
1. Create a new swiftUI project
2. Add LiveViewNative
3. Product -> Archive

**Output**
Build failed

**Comment by bcardarella** [comment]
are you pulling from `HEAD` on `main` or tagged version?

**Comment by pshoukry** [comment]
@bcardarella `main`

**Comment by pshoukry** [comment]
I can also reproduce with `0.1.1` and `0.1.2`

**Comment by carson-katri** [comment]
@pshoukry Can you check if `BuiltinRegistryGenerator` is included in the *Frameworks, Libraries, and Embedded Content*

**Comment by pshoukry** [comment]
@carson-katri Yes it is, I also tried:
1. Creating a complete new project not using lvn.install and adding Liveviewnative by hand
2. Removing the both Liveviewnative and BuiltinRegistryGenerator and adding them by hand
3. Cleaning build
4. Restarting Xcode

**Comment by carson-katri** [comment]
@pshoukry Ok, please remove `BuiltinRegistryGenerator` from the list. Only the `LiveViewNative` library should be included. Also, try using this branch which fixes a bug that crashed the Swift compiler in release configuration: https://github.com/liveview-native/liveview-client-swiftui/pull/1189

**Comment by pshoukry** [comment]
@carson-katri I am now getting a silent error ( build just fails ) the steps I did:
1. generate completely new elixir project and add deps
2. `mix lvl.install` and select defaults
3. Add Liveview native
4. remove `navigationMode: .replaceOnly` which breaks the build
5. Check `BuiltinRegistryGenerator` isn't in Frameworks, Libraries and Embedded Content
6. Build -> Fails
7. Checkout the Branch you mentioned
8. Build -> Fails

**Comment by carson-katri** [comment]
Can you select *Product* > *Clean Build Folder...*, then try archiving again? Sometimes Xcode won't show the error message unless you do a clean build for whatever reason.

**Comment by pshoukry** [comment]
Same issue

**Comment by pshoukry** [comment]
@carson-katri That solved it thank you. Just for reference had to remove and re-add the package.
