### ISSUE TITLE
[Bug]: Missing project.pbxproj

### ISSUE THREAD

**Issue by zimt28** [liveview-native/liveview-client-swiftui#1188]
### What happened?

After installing liveview native using 
```elixir
{:live_view_native, "~> 0.2.0-beta.1"},
{:live_view_native_swiftui, "~> 0.2.0-beta.1"},
```
and
```elixir
 mix lvn.install
```
I can find the xcode project but not open it as it's missing a `project.pbxproj` file.

### Library Version

see comment

### Xcode Version

14.3.1

### Target Device Operating System Version

macOS 13.4

### Relevant log output

```shell
Project /Users/me/app/native/swiftui/App/App.xcodeproj cannot be opened because it is missing its project.pbxproj file.
```

**Comment by bcardarella** [comment]
@zimt28 you'll want to follow these installation docs: https://hexdocs.pm/live_view_native/installation.html

The one change not noted in the docs yet is that in your Phoenix app you'll need to change `floki` to run in all environments (remove `only: :test` from the tuple)

**Comment by bcardarella** [comment]
@zimt28 we did a release last night. v0.2.0-beta.1 is out

**Comment by zimt28** [comment]
Yes, I followed the instructions just in case that wasn't clear – using `{:live_view_native, "~> 0.2"}` as suggested didn't work, so I specified the beta version. I also removed the `only: :test` because mix was complaining. Is there anything else I need to do? If not, this still looks like a bug to me

**Comment by bcardarella** [comment]
@zimt28 I will be releasing an install video in a few hours as I just woke up. It may be easier to follow along in that.

**Comment by zimt28** [comment]
@carson-katri I tried that a couple of times, but now not even the xcode project will be generated. I'm pretty sure I've set up everything as suggested by the installation docs but I'll wait for the video just to be sure.

**Comment by zimt28** [comment]
@carson-katri Looks like I've done everything correctly (there isn't much to do wrong either) and there are some compilation errors I missed:
```
clang-16: error: unknown argument: '-index-store-path'
clang-16: error: no such file or directory: '/Users/me/dev/app/test/_build/tmp/xcodegen/.build/arm64-apple-macosx/debug/index/store'
clang-16: warning: overriding '-mmacos-version-min=11.0' option with '-target arm64-apple-macosx10.13' [-Woverriding-t-option]
clang-16: error: unknown argument: '-index-store-path'
clang-16: error: no such file or directory: '/Users/me/dev/app/test/_build/tmp/xcodegen/.build/arm64-apple-macosx/debug/index/store'
clang-16: warning: overriding '-mmacos-version-min=11.0' option with '-target arm64-apple-macosx10.13' [-Woverriding-t-option]
clang-16: error: unknown argument: '-index-store-path'
clang-16: error: no such file or directory: '/Users/me/dev/app/test/_build/tmp/xcodegen/.build/arm64-apple-macosx/debug/index/store'
clang-16: warning: overriding '-mmacos-version-min=11.0' option with '-target arm64-apple-macosx10.13' [-Woverriding-t-option]
clang-16: error: unknown argument: '-index-store-path'
clang-16: error: no such file or directory: '/Users/me/dev/app/test/_build/tmp/xcodegen/.build/arm64-apple-macosx/debug/index/store'
clang-16: warning: overriding '-mmacos-version-min=11.0' option with '-target arm64-apple-macosx10.13' [-Woverriding-t-option]
clang-16: error: unknown argument: '-index-store-path'
[0/7] Compiling api.c
```
Should I open a new issue or is this one fine?

**Comment by bcardarella** [comment]
@zimt28 are you on the Elixir slack? I think it may be best if I can pair with you on this. As a matter of reference, with LVN we have a ton of moving parts between the Elixir version, Erlang version, Swift version, xcode version, etc... and when something "works for me" but doesn't work for you we want to dig in and see what's going on. It may be easiest if we can just get onto a call

**Comment by bcardarella** [comment]
btw, I don't know why I closed the issue. I think I hit that button but mistake earlier. Sorry about that.

**Comment by carson-katri** [comment]
You need Xcode 15 or higher to run LiveView Native.

**Comment by bcardarella** [comment]
@carson-katri good catch

@zimt28 we made a conscious decision to target more leading-edge Swift/SwiftUI that gives us more options and less constraints on the implementation. We'll probably be defining our compatibility matrix soon but for the time being it is xcode >= 15 as Carson mentioned.

**Comment by zimt28** [comment]
Thanks for the hint! I'm using Nix, which might be part of the problem, but I was able to finish the installation by upgrading to Xcode 15 and using clang from the Xcode installation by adding 
```
export PATH=$(xcodebuild -find clang | xargs dirname):$PATH
```
to my environment 🥳

**Comment by zimt28** [comment]
One addition: Using Xcode clang broke the `bcrypt_elixir` compilation for me, but the following worked:
```bash
> mix deps.compile bcrypt_elixir --force
> export PATH=$(xcodebuild -find clang | xargs dirname):$PATH
> mix lvn.install
```
