### ISSUE TITLE
Allow for composing helpers in the rules parser

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1192]
We want to support the following situation:

```
"bg-color" do
  backround(to_ime(attr("bg-color")))
end
```

Right now it fails but what we want is to allow for dynamic member expressions to be formed in the AST derived from the element attribute values. The following AST node should generate:

```
{:., [], [{:__attr__, [], ["bg-color]}]}
```

**Comment by bcardarella** [comment]
Here is the new syntax that should be validated to work:

```elixir
"bg-color" do
  backround(.attr("bg-color"))
end
```

the resulting AST would be the same

```elixir
{:., [], [{:__attr__, [], ["bg-color]}]}
```

**Comment by NduatiK** [comment]
Should the resulting AST have a `nil` (the dot applies one thing on another)

```elixir
{:., [], [nil, {:__attr__, [], ["bg-color"]}
```

**Comment by bcardarella** [comment]
@NduatiK I'd like to spend some more time thinking about the syntax here, I'm not super convinced on `.attr` in this case.

**Comment by NduatiK** [comment]
Here's a suggestion. What about the `@`? After all, we are pulling values defined on the component, similar to how one accesses `@class` from inside a function component? I'm not sure whether dashes are supported though (`bg-color` vs `bg_color`)

```elixir
background(.@bg_color))
```

**Comment by bcardarella** [comment]
So I much prefer the syntax of the `@` over `attr(...)` and I much prefer the moustache `{ ... }` syntax over EEx for interpolation `<%= ... %>` but my concern is that we'd be introducing syntax that we'd have to deviate from for a future platform that may use it. The `@` and `{ .. }` syntaxes are fairly commonly used in languages. They `{ .. }` is technically in the SwiftUI modifier syntax as closures but we happen to be working around them. So if we use these now are we going to have fork syntax on a per-platform basis if there are conflicts with the syntax?

I think it may be worth me looking into the Jetpack and WinUI 3 syntaxes to determine if this is true or not.

Furthermore, the `{ ... }` syntax has been defined in meaning within the heex templates. We want pure value insertion here, we don't want to run through a protocol to insert `"` wrappings.

**Comment by NduatiK** [comment]
From my research, `{ .. }` is used for closures in Jetpack/SwiftUI, which we will never support since the server can't inject native code into these compiled languages. WinUI 3 is XML based, so no conflicts there.

But your caution is justified, better to make the right decision this early on.

**Comment by bcardarella** [comment]
Closing as no longer valid
