### ISSUE TITLE
Support @attr syntax in style sheet.

### ISSUE THREAD

**Issue by NduatiK** [liveview-native/liveview-client-swiftui#1195]
Instead of `attr("foobar")` we should just support `@foobar`
 (would need to support hyphenation `@foo-bar`)

that way this:
```elixir
"color" do
  foregroundStyle(to_ime(attr("color")))
end
```

would become:
```elixir
"color" do
  foregroundStyle(.{@color})
end
```

**Comment by AZholtkevych** [comment]
We gonna rethink the use of @ symbol. From: @bcardarella

**Comment by AZholtkevych** [comment]
Won't fix. According to Brian
