### ISSUE TITLE
LiveView Native Clients: Use uniffi bindings for uses of liveview-native-core-swift

### ISSUE THREAD

**Issue by simlay** [liveview-native/liveview-client-swiftui#1210]
With https://github.com/liveview-native/liveview-native-core/pull/43, we can move away from hand written bindings in https://github.com/liveview-native/liveview-native-core-swift/. There are some changes required for this transition.

**Comment by AZholtkevych** [comment]
@carson-katri @nelson-glauber would you mind reviewing those PRs, please?
