### ISSUE TITLE
GeometryReader

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1218]
Can we support the GeometryReader view?

https://developer.apple.com/documentation/swiftui/geometryreader

**Comment by carson-katri** [comment]
My opinion is that `GeometryReader` falls into the category of Views that require custom Swift implementations.

It fills the parent and passes its size down to the children. So to use it from a template, you would need to do something like this:
```ex
def render(assigns) do
  ~SWIFTUI"""
  <GeometryReader phx-change="size-changed">
    ... some content that uses @size to layout elements ...
  </GeometryReader>
  """
end

def handle_event("size-changed", size, socket) do
  {:noreply, assign(socket, size: size)
end
```

In SwiftUI, you can typically access the size right away inside of the `GeometryReader`. However, in LVN you would need to wait for the event to be handled, then the child would update its rendering with the new size. This would cause some visual hitches as the content renders once without knowing the size, then redraws once that event is received. So it would probably be best to discourage using it if we did support it.

Also, while using `GeometryReader` can make certain layouts easier, it is rarely most "correct" way of creating them. Especially with the `Layout` protocol being introduced in SwiftUI, there are very few cases where a `GeometryReader` would be needed.
