### ISSUE TITLE
Display the dead render while the socket connects

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1229]
Currently we display a loading indicator while the socket connects. According to @carson-katri Now that we have platform-specific dead renders, we could now display the actual page content instead (likely with the disabled modifier applied to the views until the socket connects.

This would improve our initial page load time.

**Comment by bcardarella** [comment]
I'm going to close this as wontfix. We don't want to use the deadrender until we have a solution for auth state management.
