### ISSUE TITLE
Customizable `LiveView` state indicator Views

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-swiftui#1232]
Currently, customizing the loading, error, etc. states of a `LiveView` requires a `RootRegistry`. This API could be simplified by providing extra `ViewBuilder` closures on the `LiveView` initializer:

```swift
LiveView(.localhost) {
  ProgressView("Loading")
} error: { error in
  #if DEBUG
  Text(error.localizedDescription)
  #else
  Text("An error occurred")
  #endif
} reconnecting: { content in
  content
    .overlay {
      Text("Reconnecting")
    }
} disconnected: {
  Text("Failed to connect")
}
```

These arguments would be given priority over the `RootRegistry`. If they are not provided, the Views in the `RootRegistry` will be used.

**Comment by bcardarella** [comment]
This looks good to me, can it be promoted out of Draft yet or does it require more work?

**Comment by carson-katri** [comment]
@bcardarella It doesn't have the `reconnecting` state yet. I also had some questions about the approach using the macro.
