### ISSUE TITLE
Should stylsheets be embedded or a separate GET?

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1235]
Right now stylesheets are embedded into the root layout. But, we haven't yet had a very large app. With the boot time of the app being dictated by the the dead render GET then parsing that document and finally making the LV connection if there is a large stylesheet that is embedded into the dead render it will impact the boot time and any re-render of each app.

If we instead link to the stylesheet via a url we could fingerprint the stylesheet and cache it. This way when we re-render the app we can inspect the fingerprint of the url to determine if it should bust the cache or not. If not, we pull from cache rather than GET.

If we go this way I think a larger conversation should be had about a general asset cache. We'd want to cache things like images using the same method. From a simple search it does't seem that `AsyncImage` doesn't cache, but someone shared their solution with a `CachedAsyncImage` view they wrote https://stackoverflow.com/a/69666892/366782

**Comment by carson-katri** [comment]
We need to wait for the stylesheet to be loaded and parsed to display the content anyways, otherwise you'll get one initial render without styles then have the styles appear after the parsing is done.

**Comment by bcardarella** [comment]
So for this the concern is that if we have a rather large stylesheet if it is being embedded into the document then we have to pay the network cost every time on the dead render. If instead it is a link with a cache bust QP on the url we can decide at render time of that document if we need to fetch it again based upon the caching strategy.
