### ISSUE TITLE
Proposal: attr names follow original casing in the SwiftUI docs

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1241]
We currently have a convention that if the docs have a `fooBar` casing this becomes `foo-bar` in our templates. However, this is an artifact from very early in the project before we could override any of the casing in the templates. Now we can and we also are following nearly identically the casing and naming for views and modifiers. We should consider reverting the hyphenation on attribute names.

I'd like to hear thoughts on this and if there are any issues with doing this?

The first one that  comes to mind is that we cannot use `kino` or other document query libs as they all downcase everything. This is an existing problem for us either way as we need the casing preserved for tag names so this problem needs to be addressed.

I have confirmed that our template engine preserves the casing

**Comment by bcardarella** [comment]
@carson-katri wanted to get your thoughts on this. This came up again last night at the Boston workshop where people wondered why we followed convention everywhere but for attrs. Unless there is a good argument against it I think I'd like to migrate to this within the v0.3.0 cycle

**Comment by carson-katri** [comment]
I have no problems with switching to this casing.

**Comment by bcardarella** [comment]
Is it a heavy lift to switch over?

**Comment by carson-katri** [comment]
Not particularly, better to do it now before too many projects are made using snake-case.

**Comment by bcardarella** [comment]
Agreed. @AZholtkevych we'll include this in scope for v0.3.0 release cycle.

**Comment by carson-katri** [comment]
One issue that came to mind is consistency with `phx-click`, `phx-change`, etc. Is this a concern?

**Comment by bcardarella** [comment]
@carson-katri those should remain kebab-case. Is it an issue to keep both?

**Comment by bcardarella** [comment]
meaning do we care if there is a mix of kebab-case and camelCase?

**Comment by carson-katri** [comment]
I was only concerned about the consistency, there's no technical limitation preventing them from both being used.

**Comment by bcardarella** [comment]
I think in this case its just a matter of what the API is. In the case of SwiftUI we're simply following the casing and in case of Phoenix events we follow that casing

**Comment by bcardarella** [comment]
@AZholtkevych let's put this in scope for v0.3.0
