### ISSUE TITLE
[Bug]: View hierarchy appears to be too full

### ISSUE THREAD

**Issue by jtormey** [liveview-native/liveview-client-swiftui#1242]
### What happened?

On inspecting the view hierarchy for an app, see many more views than expected. Almost like each view is being created multiple times. It feels wrong, though this could come from my inexperience with Xcode + SwiftUI.

<img width="1367" alt="Screenshot 2024-01-23 at 9 24 49 PM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/8642682/702befac-c3ad-4b04-9e25-7d8e0eb49e25">

There are also many log lines that seem suspiciously related:

<img width="911" alt="Screenshot 2024-01-23 at 9 42 56 PM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/8642682/9e605de5-f3cb-405f-af8c-faf0180df96a">

### Library Version

755a14da9941221c539ae63dbef2de4afce41d6f

### Xcode Version

15.2 (15C500b)

### Swift Version

Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

17.1

**Comment by bcardarella** [comment]
@jtormey I know its a bit of work but are you able reproduce the same views in SwiftUI without LVN and see if the view hierarchy complexity still exists?

**Comment by jtormey** [comment]
I recreated part of the view tree in SwiftUI, and it's about the same as what LVN produces. I just misunderstood what xcode was showing me.

It looks like this actually isn't a problem and the error logs I'm seeing are unrelated. Thanks!

<img width="938" alt="Screenshot 2024-01-23 at 10 14 43 PM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/8642682/483ba0ff-2b20-4b78-9ff6-cc6d49f70965">

**Comment by carson-katri** [comment]
@jtormey Can you click the purple warning indicator and see if it indicates where the `Accessing StateObject's object without being installed on a View.` error is being triggered from?
