### ISSUE TITLE
Proposal: Addressing closures

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1243]
Example, in `AsyncImage` a content closure can be passed to inspect the phase state to render out if the images loads or there is some type of failure:

```swift
AsyncImage(url: URL(string: "https://example.com/icon.png")) { phase in
    if let image = phase.image {
        image // Displays the loaded image.
    } else if phase.error != nil {
        Color.red // Indicates an error.
    } else {
        Color.blue // Acts as a placeholder.
    }
}
```

we currently don't have a convention to manage this in LVN. Our own `AsyncImage` implementation hard codes these phases:

https://github.com/liveview-native/liveview-client-swiftui/blob/main/Sources/LiveViewNative/Views/Images/AsyncImage.swift#L49-L60

But we have a way to pass templates off to a closure. If `phase` is the conventional term used in these cases I'd like to propose the following:

```heex
<AsyncImage url={@url} >
  <Image class="foo-bar" phase="image" />
  <Text phase="error">Error!</Text>
</AsyncImage>
```

this convention should carry across all views

**Comment by bcardarella** [comment]
Any child elements with the attr `phase` should be lifted out same as with `template`

**Comment by bcardarella** [comment]
@carson-katri I realize `phase` isn't a standard variable on all views, that wasn't what I was suggesting. Considering we are the ones implementing the views we have control over what that variable is.

I'm opposed to using `template` as it is polluting the utility of the that attribute. For example, could we run into an issue where both a content in the closure and a content view for a modifier would be necessary now we only have a single attribute to do that in? Having to share responsibility I believe is bad API design.

We can simply just define what the closure name is for the given view.

**Comment by bcardarella** [comment]
I went back and looked over a few examples. I am convinced that we need a way to represent this in markup. But I don't yet have a clean way to do this.

For the `AsyncImage` example or any closure that takes arguments, I don't think we should deviate from the current API on what `template` means. What we do need though is a way to inform a view outside of the modifier system which templates are used for which named closure:

```swift
AsyncImage(url: URL(string: "...")) { phase

}
```

this particular form of `AsyncImage` is the one we should use I believe because it has more nuanced control over the phases. Why the other form doesn't have a named closure beyond the `success` and `placeholder` is beyond me but here we are. In this case we could represent it like so:

```html
<AsyncImage content={:phase} url={@url}>
  <Group template={:phase}>
    <Image class="resizable phase={:success}/>
    <Text phase={:error}>Error!</Text>
    <ProgressView phase={:placeholder}/>
  </Group>
</AsyncImage>
```

or a form that coalesces a the template name:

```html
<AsyncImage content={:phase} url={@url}>
  <Image template={:phase} class="resizable enum={:success}/>
  <Text template={:phase} enum={:error}>Error!</Text>
  <ProgressView template={:phase} enum={:placeholder}/>
</AsyncImage>
```

This becomes more tricky when it comes to views like `GeometryReader`. I do not think at this time we want to expand the scope of this prorposal for the full surface area of closures. But for cases of `enum` states it may be valid.

What we want to avoid is a specific DSL just for `AsyncImage`, we need to find a solution that is going to not just work for the SwiftUI views but any view of any complexity that others may write in the future.

**Comment by bcardarella** [comment]
@carson-katri something that would really open up some possibilties for us is if we accepted some encoding within the attributes. We could easily do a simple version of the modifier parser to produce an AST node for runtime parsinga and use. As long as it doesn't significantly affect the render performance.

**Comment by carson-katri** [comment]
Here's a possible solution:

1. Use `argument[value]` to specify a template for a given value of the closure argument. This would typically be an enum case, such as `empty`, `success`, or `failure`.
2. Use the element name with some boolean attribute (`image` or `error` in this case) to render an associated value from the enum case. You can put any additional attributes on this element, such as `class="resizable"`.

```html
<AsyncImage url="...">
    <Group template="phase[empty]">
        <ProgressView />
    </Group>
    <Group template="phase[success]">
        <AsyncImage image class="resizable" /> <!-- reference to evaluated image element -->
    </Group>
    <Group template="phase[failure]">
        <AsyncImage error /> <!-- reference to plain-text error description -->
    </Group>
</AsyncImage>
```

This can also be converted into a component for more natural use:
```heex
<AsyncImage.async_image url="...">
    <:empty>Loading</:empty>
    <:success :let={image}>
        <%= image %>
    </:success>
    <:failure :let={error}>
        <%= error %>
    </:failure>
</AsyncImage.async_image>
```
```elixir
defmodule AsyncImage do
  use Phoenix.Component
  use LiveViewNative.Component,
    format: :swiftui,
    as: :render

  attr :rest, :global
  slot :empty
  slot :success
  slot :failure
  def async_image(assigns) do
    ~LVN"""
    <AsyncImage {@rest}>
      <Group template="phase[empty]">
        <%= render_slot(@empty) %>
      </Group>
      <Group template="phase[success]">
        <%= render_slot(@success, ~LVN"<AsyncImage image />") %>
      </Group>
      <Group template="phase[failure]">
        <%= render_slot(@failure, ~LVN"<AsyncImage error />") %>
      </Group>
    </AsyncImage>
    """
  end
end
```

**Comment by carson-katri** [comment]
That's what I was picturing, a library that adds additional function components on top of the raw markup syntax.

I'm not sure about the template syntax myself.
`argument[case]` looks like a subscript, `argument.case` looks like a member access. Maybe `argument:case` for more of a key-value look? Or move the `argument` segment into the attribute, `template:argument="case"`

I have a prototype implementation of this syntax for `AsyncImage` and the `template` format is extracted so we can experiment with it.

**Comment by carson-katri** [comment]
I don't think the current API would be able to extend beyond enum cases. `AsyncImage` is the only example I can think of in SwiftUI. RealityKit has `Model3D` which uses a similar API to `AsyncImage`.

Here a few more complex cases, but I don't think it would be practical to implement these for SSR:

1. [`KeyframeAnimator`](https://developer.apple.com/documentation/swiftui/keyframeanimator)

```swift
KeyframeAnimator(initialValue: 0.0) { value in
    Text("Hello, world!")
        .offset(y: value)
} keyframes: { value in
    LinearKeyframe(20, duration: 3)
    SpringKeyframe(0, duration: 1)
    CubicKeyframe(-20, duration: 2)
    LinearKeyframe(0, duration: 0.5)
}
```

The `value` is updated based on the specified keyframes. This `value` can then be used within the content. In this example, the value is used as an offset for the text.

2. [`Canvas`](https://developer.apple.com/documentation/swiftui/canvas)

```swift
Canvas { context, size in
    context.fill(Circle().path(in: .init(x: 0, y: 0, width: 20, height: 20)), with: .color(.red))
    context.rotate(by: .degrees(45))
    context.stroke(Rectangle().path(in: .init(x: 10, y: 10, width: 40, height: 40)), with: .color(.red))
}
```

Canvas does not have a declarative API. To implement something like `Canvas` we would likely need a way to represent the commands as elements. Possibly something like `<svg>`. But in general, this would be better to implement as a custom View on the client side.

3. [`TimelineView`](https://developer.apple.com/documentation/swiftui/timelineview)

```swift
TimelineView(.periodic(from: startDate, by: 1)) { context in
    AnalogTimerView(date: context.date)
}
```

In this example, the `AnalogTimerView` is updated every 1 second with a new `context.date` value.

**Comment by bcardarella** [comment]
I think this keeps coming back to that we need a way to represent attribute values in a more complex fashion that simply key/value. I've been punting on this for a while but we may need to support deserialization of attributes from complex objects.

**Comment by carson-katri** [comment]
Even for more basic Views this will be helpful. For example, `LazyVGrid` needs to pass a list of `GridItem` to the `columns` attribute to configure the number/layout of the columns. If the template automatically encoded the attribute from a list, the API would be much simpler.

**Comment by bcardarella** [comment]
@carson-katri is there an easy way for the client to determine if a value should be de-serialized? What I'd like to avoid is having to declare each attribute that should be deserialized in a specific manner. Or, would that actually be more performant?

**Comment by carson-katri** [comment]
I assume it would just be the attributes that take complex values. Such as the `columns` attribute in the `LazyVGrid` example.

**Comment by bcardarella** [comment]
Right but would that mean you'd have to go back to every single view in the SwiftUI and declare how each attribute should be deserialized? Or is there a single choke point to do this?

**Comment by bcardarella** [comment]
what I'll look into today is enabling auto-serialization for `Map` within the template:

```heex
<FooBar baz={%{a: 1}} />
```

evals as

```html
<FooBar baz="{a: 1}" />
```

**Comment by bcardarella** [comment]
@carson-katri do you see us needing anything more than Map?

**Comment by carson-katri** [comment]
List values will be needed.

**Comment by bcardarella** [comment]
Went down the rabbit hole a bit here. I think this is going to be a deeper fix than I originally anticipated. I can easily expand `Phoenix.HTML.Safe` to give us what we want but that would impact the `HTML` rendering as well and we don't want to contaminate that. Instead I'll probably have to implement our own `LiveViewNative.Template.Safe` for rendering and this may require a bunch more changes to delegate to that function. Or, if I could advocate for the `Safe` handler to be part of the template compiler upstream in Phoenix itself. Either way this isn't a quick fix to do correctly. I'm going to try and grab Jose's time to discuss the best approach here this week after I dig a bit deeper, probably just make a PR upstream to get that conversation started.

**Comment by bcardarella** [comment]
Json encoded literals are now enabled: https://github.com/liveview-native/live_view_native/pull/132
