### ISSUE TITLE
Reconnecting state view is rendering in the middle

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1253]
<img width="559" alt="Screenshot 2024-02-02 at 9 59 44 AM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/18524/a9f82ddd-4f0a-4dce-a929-986b3f1b0ee4">

LVN Markup:

```heex
<VStack class="padding" alignment="leading">
  <Text class="font:title">Turtle Rock</Text>
  <HStack class="font:subheadline">
    <Text>Joshua Tree National Park</Text>
    <Spacer />
    <Text>California</Text>
  </HStack>
</VStack>
```

**Comment by carson-katri** [comment]
This is with the default generated `ContentView`, correct?

**Comment by bcardarella** [comment]
Corect. However, this was after: https://github.com/liveview-native/liveview-client-swiftui/pull/1252 but I cannot see what that extract would have pushed the content down but then again I'm very good at SwiftUI

**Comment by carson-katri** [comment]
Oh, I didn't see that PR. I'll look into it.

**Comment by bcardarella** [comment]
I wanted to get that in for the workshop last Friday but didn't want to ping you outside your working hours, otherwise I would have waited for your approval
