### ISSUE TITLE
Warning on attribute in SwiftUI

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1254]
<img width="1129" alt="Screenshot 2024-02-02 at 10 08 15 AM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/18524/9ee74121-c2b1-446b-aa1b-f731c41944a8">

Here: https://github.com/liveview-native/liveview-client-swiftui/blob/main/Sources/LiveViewNative/Property%20Wrappers/Attribute.swift#L93

**Comment by carson-katri** [comment]
Can you share the template that triggered this warning?

**Comment by bcardarella** [comment]
Sorry, that was a half-assed issue I opened. The bug is legit, I'll get the template this morning
