### ISSUE TITLE
Client doesn't attempt to reconnect if initial connection fails

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1255]
Steps to reproduce:

1. Start client without a server running
2. Wait until the `Connection Failed` error renders
3. Start the server
4. Client doesn't attempt any reconnects

The expectation would be that the client is attempting reconnects indefinitely

**Comment by bcardarella** [comment]
Reviewing this again I could have sworn I had opened an issue about this in the past but cannot find it. But I suspect this is because if these views render without a good render first then the LiveReload doesn't get setup.

**Comment by carson-katri** [comment]
That's correct. Should it automatically reconnect? Or put a button on screen to attempt a reconnect?

**Comment by bcardarella** [comment]
we want to mimic web so it should auto-reconnect

**Comment by carson-katri** [comment]
If I go to `localhost:4000` without the server running, I get an error screen in the browser. Then when I start the server, the browser doesn't do anything. I have to manually reload the page.

**Comment by bcardarella** [comment]
oh wait, I have the wrong instructions there. If your first render is an error page. So if you have a `raise` or a syntax error that will cause a server stack trace on first render. That will livereload in browser but not on SwiftUI client
