### ISSUE TITLE
LiveReload should reconnect on the current url

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1263]
When navigating away from the base url in development if LiveReload is triggered the app reloads to the original base url. Instead it should reload on the current url navigated to

**Comment by bcardarella** [comment]
we do not change the base url that we connect to for reconects, the current liveview's url is used within the params object with the channel:

https://github.com/phoenixframework/phoenix_live_view/blob/main/assets/js/phoenix_live_view/view.js#L137-L147

**Comment by bcardarella** [comment]
@simlay ☝️ Core will need to implement this behavior as well

**Comment by carson-katri** [comment]
@bcardarella So it still performs the connection from the URL that is configured on the `LiveView` SwiftUI View, but passes the last navigation path URL when joining the channel?
