### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1265]
This is on `main` right now, I cannot compile the library

<img width="2032" alt="Screenshot 2024-02-09 at 10 30 09 AM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/18524/2977fcf2-4294-458c-9617-d4c255f60ba1">

**Comment by carson-katri** [comment]
Please update the SwiftUI views in your app to the latest template views. They were updated in #1260

**Comment by bcardarella** [comment]
Closing as this was due to not using the correct version of the lib to generate the new views
