### ISSUE TITLE
[Bug]: SwiftUI Views cannot accept a `content` attribute

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1281]
### What happened?

The `Text` view's content attribute is provided inside the children of the element.

```html
<Text>content</Text>
```

However, I would expect to also be able to provide this as an attribute.

```html
<Text content="content"></Text>
```

But we currently don't seem to support this.

### Library Version

latest

### Xcode Version

latest

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

NA

**Comment by carson-katri** [comment]
You can do this with the `verbatim` or `markdown` attributes.
