### ISSUE TITLE
Simplify the addon API?

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1296]
I'm curious if it is possible to simplify the addon API. For MapKit we currently have:

```swift
addons: [MapKitRegistry<_>.self]
```

for LiveForm it looks like a new registry must be created: 

```swift
struct AppRegistries: AggregateRegistry {
    typealias Registries = Registry2<
        MyRegistry,
        LiveFormRegistry<Self>
    >
}
```

I'm wondering if something as simple this can be supported:

```swift
addons: [LiveViewNativeMapKit, LiveViewNativeLiveForm]
```

The primary library struct should have a common API, something like:

```swift
public fun addon(root: RootRegistry)
```

then within LVN itself it can iterate over the `addons` list and call `addon(self)` or whatever the proper API should be.

**Comment by carson-katri** [comment]
I was thinking about simplifying this as well. I think an API like this is the most viable:

```swift
#LiveView(
    .localhost,
    addons: [.mapKit, .liveForm, .avKit]
)
```

**Comment by bcardarella** [comment]
@carson-katri I like that. What happens if we have collision of those names between two different libs?

**Comment by carson-katri** [comment]
The compiler would complain that it's ambiguous, and you would have to fallback to the `SomeNameRegistry<_>.self` form.
