### ISSUE TITLE
[Bug]: Cannot find type 'SearchPresentationToolbarBehavior' in scope

### ISSUE THREAD

**Issue by antonioparisi** [liveview-native/liveview-client-swiftui#1297]
### What happened?

Just running a hello world using live view native. Followed the sample of latest https://github.com/liveview-native/form_demo
Everything runs smoothly on the Elixir side, except whenever I open the XCode project, trying to Build/Run it I get the following error:

![Screenshot 2024-03-24 at 14 30 25](https://github.com/liveview-native/liveview-client-swiftui/assets/1324178/b6647874-d762-42dc-abff-0cc97f460ebb)

Any ideas?

### Library Version

latest off the `main` branch.

### Xcode Version

15.0.1

### Swift Version

swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)

### On which device or simulator are you running into the problem?

iPhone, iPad

### Target Device Operating System Version

17.0.1

**Comment by antonioparisi** [comment]
Will give it a try to update XCode to the latest version and use iOS 17.4

**Comment by bcardarella** [comment]
@antonioparisi We were using the form-demo repo as a playground to work on some still in-flight updates to LiveForm. I suspect what you're seeing is the result from using `main` or a release version on the swiftui libs where you want to be using the form-demo branches for both the SwiftUI client and LiveForm libs. As this is still not merged it will be unstable. I'm hoping we merge this upcoming week.

**Comment by antonioparisi** [comment]
@bcardarella The issue was lying on the XCode side, by installing the latest XCode version (15.3) and using the latest iOS 17.4 works fine as expected, the error disappeared.

Thanks so much for the quick reply anyway, appreciated.

**Comment by bcardarella** [comment]
Good to here, the nagging xcode issues have been really weighing on me. After v0.3 is released I am going to focus on how we can make this a less crappy experience. I've been bit by xcode bombing on me multiple times and from what I've read in the iOS dev community they just put up with it. I'm invested to find a more stable position for LVN where we can not wrestle with the Apple dev environment so much.
