### ISSUE TITLE
Feature: interfacing with on-device data from sensors or frameworks

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1299]
I was asked about if accessing a framework like `FinanceKit` would be possible in LVN, I figured yet but if we don't currently have an api for doing this we probably should. It's going to seem convoluted but in the case of `FinanceKit` I think the data should be sent to the server over a `phx` event so that server can decide how it wants to represent that data in the app screen. It seems kind of stupid to send data from the phone, render, then send back to the phone but I don't think it makes sense to mix any render state changes client-side

**Comment by carson-katri** [comment]
It sounds like this is proposing creating elements that allow data to be pushed up to the server with a customizable event name:

```html
<FinanceKit phx-change="receive-finance-data" />
```

But for something custom like this, is there a reason why they can't use the existing `pushEvent`/`receiveEvent` API? This provides more flexibility. Also they will need to write logic in Swift to configure what data should be collected, request permission from the user, etc.

I think this would more closely match LiveView itself, which provides a `pushEvent` function to send information collected via JavaScript to the server.

**Comment by bcardarella** [comment]
yeah that makes sense

**Comment by bcardarella** [comment]
Closing as this is a forever-issue that we can address per-addon
