### ISSUE TITLE
Custom colors can't be applied through inline styles

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1331]
It seems modifiers such as the following:

```swiftui
foregroundStyle(Color(.sRGB, red: 0.4627, green: 0.8392, blue: 1.0))
```

can be applied through stylesheets, but not through the `style` attribute as a utility style.

**Comment by BrooklinJazz** [comment]
This is also true for colors in the asset catalog.

```elixir
foregroundStyle(Color("MyColor"))
```

**Comment by BrooklinJazz** [comment]
The first issue was because we don't support whitespace in utility styles, that's resolved by removing whitespace.

The second issue is a bug because we don't handle quotes.

**Comment by carson-katri** [comment]
For quotes, have you tried using `Color(['MyColor'])`? The `['']` syntax was built in to the original implementation of utility classes to match how Tailwind handles string values. However, I'm not sure if it is part of the new method.

You might also be able to use single quotes for your attribute, then the double quotes inside might work:
```html
<Element class='foregroundStyle(Color("MyColor"))' />
```

**Comment by BrooklinJazz** [comment]
@carson-katri I tried both patterns and neither worked for me.

Apologies for the late response.

**Comment by carson-katri** [comment]
This should work with the `style` attribute now.

**Comment by BrooklinJazz** [comment]
@carson-katri I can't seem to get this to work. I've tried:

```
<Text style={"foregroundStyle(Color('MyColor'))"}>Hello, from LiveView Native!</Text>
<Text style={"foregroundStyle(Color(['MyColor']))"}>Hello, from LiveView Native!</Text>
<Text style={'foregroundStyle(Color("MyColor"))'}>Hello, from LiveView Native!</Text>
<Text style={"foregroundStyle(Color(\"MyColor\"))"}>Hello, from LiveView Native!</Text>
```

<img width="479" alt="Screenshot 2024-05-27 at 2 54 49 PM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/14877564/10e48afc-7e4c-43c2-b2ce-8b474e22cb1e">


None of them work. I do have "MyColor" defined in the asset catalog.

Here's my mix deps incase it's a version thing:

```elixir
      {:live_view_native, github: "liveview-native/live_view_native", override: true},
      {:live_view_native_swiftui, github: "liveview-native/liveview-client-swiftui", branch: "main"},
      {:live_view_native_jetpack,
       github: "liveview-native/liveview-client-jetpack", tag: "0.3.0-alpha.3"},
      {:live_view_native_html,
       github: "liveview-native/live_view_native_html", tag: "0.3.0-alpha.3"},
      {:live_view_native_stylesheet, github: "liveview-native/live_view_native_stylesheet", branch: "main", override: true},
      {:live_view_native_live_form, "~> 0.3.0-rc.2"}
```

**Comment by bcardarella** [comment]
I'll check this today. It should be working

**Comment by BrooklinJazz** [comment]
@bcardarella is this available on a particular branch? I tried to reproduce yesterday but haven't been able to.

Here's the mix file of the kino live view native project:
```elixir
      {:live_view_native, github: "liveview-native/live_view_native", override: true},
      {:live_view_native_swiftui, github: "liveview-native/liveview-client-swiftui", branch: "main"},
      {:live_view_native_jetpack,
       github: "liveview-native/liveview-client-jetpack", tag: "0.3.0-alpha.3"},
      {:live_view_native_html,
       github: "liveview-native/live_view_native_html", tag: "0.3.0-alpha.3"},
      {:live_view_native_stylesheet, github: "liveview-native/live_view_native_stylesheet", branch: "main", override: true},
      {:live_view_native_live_form, "~> 0.3.0-rc.2"}
```

**Comment by bcardarella** [comment]
it was on `main`. I'll pair with you today to see what's up.
