### ISSUE TITLE
Out of Date Documentation

### ISSUE THREAD

**Issue by BrooklinJazz** [liveview-native/liveview-client-swiftui#1332]
Our Documentation at https://liveview-native.github.io/liveview-client-swiftui/documentation/liveviewnative uses old versions of modifier syntax

**Comment by carson-katri** [comment]
I believe we are moving everything into hex docs, so we could probably take that documentation page down.

**Comment by bcardarella** [comment]
agreed, also that guide from way back we want to take down as well
