### ISSUE TITLE
CoreComponent updates

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1340]
We will want to cover some remaining CoreComponents prior to v0.3

* [`modal`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L44)
* [`flash`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L108)
* [`flash_group`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L147)
* [`label`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L399)
* [`list`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L538)
* [`back`](https://github.com/phoenixframework/phoenix/blob/main/installer/templates/phx_web/components/core_components.ex#L561)

We should decide which, if any, we have to punt on. (I'm guessing `back` ?)

These will go into https://github.com/liveview-native/liveview-client-swiftui/blob/main/priv/templates/lvn.swiftui.gen/core_components.ex

That file is generated into a project with `mix lvn.swiftui.gen`

LiveForm must be a dependency of the project to ge the LiveForm related components and `import` to render when generating the file.

**Comment by carson-katri** [comment]
I agree `back` is probably not useful for SwiftUI, as the `<NavigationStack>` adds back buttons automatically.

SwiftUI has a `Label` element, but it doesn't work like the HTML `<label>`. The `<label>` in HTML has a `for` attribute that links it to a form control of the same name.

From MDN:
```html
<label for="cheese">Do you like cheese?</label>
<input type="checkbox" name="cheese" id="cheese" />
```

SwiftUI's label is just a visual icon/title combo. It doesn't link with form controls. Instead, you typically nest a label within an input.

```html
<Toggle name="cheese" id="cheese">
  <Label systemImage="fork.knife">Do you like cheese?</Label>
</Toggle>
```

**Comment by carson-katri** [comment]
Here's an implementation for the `<.flash>` and `<.flash_group>` components using alerts:

```ex
@doc """
Renders flash notices.

## Examples

    <.flash kind={:info} flash={@flash} />
    <.flash kind={:info} phx-mounted={show("#flash")}>Welcome Back!</.flash>
"""
attr :id, :string, doc: "the optional id of flash container"
attr :flash, :map, default: %{}, doc: "the map of flash messages to display"
attr :title, :string, default: nil
attr :kind, :atom, values: [:info, :error], doc: "used for styling and flash lookup"
attr :rest, :global, doc: "the arbitrary attributes to add to the flash container"

slot :inner_block, doc: "the optional inner block that renders the flash message"

def flash(assigns) do
  assigns = assign_new(assigns, :id, fn -> "flash-#{assigns.kind}" end)

  ~LVN"""
  <% msg = render_slot(@inner_block) || Phoenix.Flash.get(@flash, @kind) %>
  <VStack
    :if={msg != nil}
    class="hidden alert-[attr(title)]-isPresented:[attr(presented)]-actions::actions-message::message"
    title={@title}
    presented={msg != nil}
    id={@id}
    {@rest}
    phx-change="lv:clear-flash"
    phx-value-key={@kind}
  >
    <Text template="message"><%= msg %></Text>
    <Button template="actions">Ok</Button>
  </VStack>
  """
end

@doc """
Shows the flash group with standard titles and content.

## Examples

    <.flash_group flash={@flash} />
"""
attr :flash, :map, required: true, doc: "the map of flash messages"
attr :id, :string, default: "flash-group", doc: "the optional id of flash container"

def flash_group(assigns) do
  ~LVN"""
  <Group id={@id}>
    <.flash kind={:info} title={"Success!"} flash={@flash} />
    <.flash kind={:error} title={"Error!"} flash={@flash} />
  </Group>
  """
end
```

You can include it in the `app.swiftui.neex` template:

```heex
<%= @inner_content %>
<.flash_group flash={@flash} />
```

Then it will respond to `put_flash`:

```ex
def handle_event("flash", _params, socket) do
  {:noreply, put_flash(socket, :info, "This is an info flash")}
end

def handle_event("flash-err", _params, socket) do
  {:noreply, put_flash(socket, :error, "This is an error flash")}
end
```


https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/5e496735-97c1-4b34-afe6-b4981c168e11

**Comment by bcardarella** [comment]
Are the web flash components rendering modals or alerts?

**Comment by carson-katri** [comment]
https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/0bce02ba-bcaf-459b-b8e8-18feafa584ae

Here is the web version of flash

**Comment by bcardarella** [comment]
Works for me 😄

**Comment by carson-katri** [comment]
Here is an implementation of the `<.modal>` component. However, it doesn't support the `on_cancel` argument. That argument in the original component uses the `JS` struct to perform some action. On native, `on_cancel` could potentially send an event instead.

```ex
@doc """
Renders a modal.

## Examples

    <.modal id="confirm-modal">
      This is a modal.
    </.modal>

"""
attr :id, :string, required: true
attr :show, :boolean, default: false
slot :inner_block, required: true

def modal(assigns) do
  ~LVN"""
  <VStack
    id={@id}
    :if={@show}
    class="sheet-isPresented:[attr(presented)]-content::content"
    presented={@show}
  >
    <VStack template="content">
      <%= render_slot(@inner_block) %>
    </VStack>
  </VStack>
  """
end
```

```heex
<.modal show id="confirm-modal">
  This is a modal.
</.modal>
```


https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/c1c20466-063a-4b8a-9e59-c27295eac13d

**Comment by carson-katri** [comment]
Here is an updated `<.table>` component. The existing one was not fully implemented.

```ex
@doc ~S"""
Renders a table with generic styling.

## Examples

    <.table id="users" rows={@users}>
      <:col :let={user} label="id"><%%= user.id %></:col>
      <:col :let={user} label="username"><%%= user.username %></:col>
    </.table>
"""
attr :id, :string, required: true
attr :rows, :list, required: true
attr :row_id, :any, default: nil, doc: "the function for generating the row id"

attr :row_item, :any,
  default: &Function.identity/1,
  doc: "the function for mapping each row before calling the :col and :action slots"

slot :col, required: true do
  attr :label, :string
end

slot :action, doc: "the slot for showing user actions in the last table column"
def table(assigns) do
  ~LVN"""
  <Table id={@id}>
    <Group template="columns">
      <TableColumn :for={col <- @col}><%= col[:label] %></TableColumn>
      <TableColumn :if={@action != []} />
    </Group>
    <Group template="rows">
      <TableRow
        :for={{row, i} <- Enum.with_index(@rows)}
        id={(@row_id && @row_id.(row)) || i}
      >
        <VStack :for={col <- @col}>
          <%= render_slot(col, @row_item.(row)) %>
        </VStack>
        <HStack>
          <%= for action <- @action do %>
            <%= render_slot(action, @row_item.(row)) %>
          <% end %>
        </HStack>
      </TableRow>
    </Group>
  </Table>
  """
end
```

It does not support the `row_click` attribute, as SwiftUI's `Table` only supports a `selection` attribute and `phx-change` on the `Table` itself, not individual rows.

```heex
<.table id="users" rows={@users}>
  <:col :let={user} label="id"><%= user.id %></:col>
  <:col :let={user} label="username"><%= user.username %></:col>
  <:action>
    <Button>Save</Button>
  </:action>
  <:action>
    <Button role="destructive">Delete</Button>
  </:action>
</.table>
```

> [!NOTE]
> Table renders as a List on iPhones.

<img width="568" alt="Screenshot 2024-05-07 at 3 02 43 PM" src="https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/6469bf9d-e07e-425b-a9de-6f5ae4f85aa5">

**Comment by carson-katri** [comment]
Here is an implementation for the `<.list>` component:

```ex
@doc """
Renders a data list.

## Examples

    <.list>
      <:item title="Title"><%%= @post.title %></:item>
      <:item title="Views"><%%= @post.views %></:item>
    </.list>
"""
slot :item, required: true do
  attr :title, :string, required: true
end

def list(assigns) do
  ~LVN"""
  <List>
    <LabeledContent :for={item <- @item}>
      <Text template="label"><%= item.title %></Text>
      <%= render_slot(item) %>
    </LabeledContent>
  </List>
  """
end
```

It works the same as the web version:
```heex
<.list>
  <:item title="Title"><%= @post.title %></:item>
  <:item title="Views"><%= @post.views %></:item>
</.list>
```

![Simulator Screenshot - iPhone 15 Pro - 2024-05-07 at 15 18 44](https://github.com/liveview-native/liveview-client-swiftui/assets/13581484/ac4194c2-860e-4d5f-b587-cfd24a6efa84)

**Comment by carson-katri** [comment]
These new components are available on `main`.
