### ISSUE TITLE
attr typecasting

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1353]
In class rules the attr values are string, we should allow for typecasting:

```swift
foregroundStyle(Color(red: attr("red", :float), green: attr("green", :float), blue: attr("blue", :float))
```

results in:

```elixir
{:foregroundStyle, [], [{:Color, [], [red: {:__attr__, [], ["red", :float]}, green: {:__attr__, [], ["green", :float]}, blue: {:__attr__, [], ["blue", :float]}]}
```

**Comment by bcardarella** [comment]
In this case the `Color` modifier was not accepted text representations of a float. I tried:

```
foregroundStyle(Color(red: attr("red"), green: attr("green"), blue: attr("blue")))
```

with:

```heex
<Rectangle red="0.5" green="0.1" blue="0.7" />
```

with no luck until I changed to the more explicit float:

```
foregroundStyle(Color(red: 0.5, green: 0.1, blue: 0.7))
```

**Comment by bcardarella** [comment]
@carson-katri ah ok, out of curiosity is there a way to determine which other views within the client would require `AttributeDecodable` or do we have to add as we go?

**Comment by carson-katri** [comment]
There's a list in the modifier generator. In this case, `Color` is already attribute decodable, it just needs to extend that to its arguments

https://github.com/liveview-native/liveview-client-swiftui/blob/a636966a05f8e5a7782171c578244b40946749b2/Sources/ModifierGenerator/Signature.swift#L281-L299

**Comment by bcardarella** [comment]
@carson-katri is this still an issue?

**Comment by carson-katri** [comment]
No, color was improved to better support attr.
