### ISSUE TITLE
[Bug]: Energy impact reporting high

### ISSUE THREAD

**Issue by michaelst** [liveview-native/liveview-client-swiftui#1362]
### What happened?

![image](https://github.com/liveview-native/liveview-client-swiftui/assets/4080508/686e1fe8-c159-4eaf-a636-f477c2ddd26b)

basic usage showing a static page is using a lot of energy and making my phone hot

### Library Version

main branch

### Xcode Version

Version 15.4 (15F31d)

### Swift Version

swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4) Target: arm64-apple-macosx14.0

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

17.5 (not simulator)

**Comment by carson-katri** [comment]
Apple recommends reducing CPU usage if thermal state is too high (in my tests we stay in "Nominal" and "Fair"), but in your screenshot its only actively using 8%, so there isn't much to reduce there.

So my guess is this is a combination of the network connection being constant with LVN, and the debugger being attached. You could try a release build without the debugger and see if that makes any difference in the thermal state.

**Comment by bcardarella** [comment]
Will close for now

**Comment by bcardarella** [comment]
We have another report of a high energy usage. Re-opening so we can track and gather data

**Comment by bcardarella** [comment]
We'll keep an eye on energy usage but for now we'll close this again as we don't see anything actionable as the CPU is 8%, the network is at 0Kb/s
