### ISSUE TITLE
tabItem modifier doesn't conform entirely to Apple documentation

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1365]
```swift
tabItem(:mylabel)
```

works but from the [Apple documentation](https://developer.apple.com/documentation/swiftui/view/tabitem(_:)):

```swift
func tabItem<V>(@ViewBuilder _ label: () -> V) -> some View where V : View
```

I presume that the `_` default named argument's name is `label` so if I try:

```swift
tabItem(label: :mylabel)
```

the modifier doesn't match in the client:

```
Stylesheet parsing failed for modifier `tabItem` in class `tabItem(content: :tablabel)`:

  |
1 | tabItem(content: :tablabel)
  | ^ No matching clause found for modifier `tabItem`. Expected `tabItem(_:)`

in  (home_live.swiftui.neex:1)
```

**Comment by carson-katri** [comment]
`_` means the argument has no label. So in SwiftUI you write this as:

```swift
tabItem({ Text("Label") })
```

but this would cause an error:

```swift
tabItem(label: { Text("Label") })
// error: Extraneous argument label 'label:' in call
```

**Comment by bcardarella** [comment]
yes I saw that error and looked at the Swift source, my question is if `label` is a supported named argument in the original SwiftUI, I see it in the Apple docs or am I misunderstanding.

**Comment by carson-katri** [comment]
I think you're misunderstanding the function signature. In that example, the argument label is `_`, with the second label being `label` (for use within the function body).

When the first argument label is a wildcard `_` character, you cannot pass a label.

```swift
func myFunction(_ unlabeled: Any) -> Any {
  // use `unlabeled` in here
}

// call without a labeled argument.
myFunction(5)
myFunction(unlabeled: 5) // this form is invalid
```


A wildcard argument label does not mean the label is optional, it means the label cannot be used at the call site at all.

**Comment by bcardarella** [comment]
ah ok, it's not a named argument. That makes sense
