### ISSUE TITLE
Include i18n and l10n in interface data

### ISSUE THREAD

**Issue by jtormey** [liveview-native/liveview-client-swiftui#1379]
It would be nice to have this in rendering for i.e. getting user time zone data.

https://github.com/liveview-native/liveview-client-swiftui/blob/9fe36d46499dfe3c9af29444a03e9f94a85742b4/Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift#L524-L532

**Comment by bcardarella** [comment]
@carson-katri I think we should add two more keys:

* `i18n`
* `l10n`

These should probably be a map as well so we can add new values when necessary and not break backwards compatibility:

```
i18n: {
  language: "en-US"
},
l10n: {
  tz: "America/New_York"
}
```
