### ISSUE TITLE
[Bug]: error: Multiple commands produce 'RANDOM_PATH/.app'

### ISSUE THREAD

**Issue by rushikeshpandit** [liveview-native/liveview-client-swiftui#1393]
### What happened?

I created a new project with following dependency version.

mix.exs

{:live_view_native, github: "liveview-native/live_view_native", branch: "main", override: true},
{:live_view_native_swiftui, github: "liveview-native/liveview-client-swiftui", branch: "main"}

Also in xcode, I make sure that `LiveViewNative` dependency is pointing to `main` branch.

but still I am getting following error.

```
error: Multiple commands produce '/Users/rushikeshpandit/Library/Developer/Xcode/DerivedData/Resman-fnqbjsxsrgfenwgmqimixizklthc/Build/Products/Debug-iphonesimulator/.app'

note: Target 'Resman' (project 'Resman') has create directory command with output '/Users/rushikeshpandit/Library/Developer/Xcode/DerivedData/Resman-fnqbjsxsrgfenwgmqimixizklthc/Build/Products/Debug-iphonesimulator/.app'

note: Target 'Resman' (project 'Resman') has link command with output '/Users/rushikeshpandit/Library/Developer/Xcode/DerivedData/Resman-fnqbjsxsrgfenwgmqimixizklthc/Build/Products/Debug-iphonesimulator/.app'

Multiple commands produce '/Users/rushikeshpandit/Library/Developer/Xcode/DerivedData/Resman-fnqbjsxsrgfenwgmqimixizklthc/Build/Products/Debug-iphonesimulator/.app'
```

### Library Version

main

### Xcode Version

15.4 (15F31d)

### Swift Version

5.0

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

iPhone 15 Pro Max

**Comment by rushikeshpandit** [comment]
I have found temporary workaround for this issue as follow.
```
1. Select “PROJECT_NAME” from top left corner of xcode.
2. Select “PROJECT_NAME” under the target
3. Select “Build Settings” tab and Search for “Product Module Name” and set it’s value to “$(PRODUCT_NAME:c99extidentifier)”
4. Search for “Product Name” in the same window and set it’s value to “$(TARGET_NAME)”
5. Also make sure to “Swift Language Version” value to “Swift 5” by following the same process
```

**Comment by bcardarella** [comment]
I'll start looking into this prior to rc-2 but my immediate thought is that the new xcodegen vendored binary is the issue, as we previously were using an older release available through installation methods this vendored binary is from the repo's `main` branch and maybe their API changed

**Comment by bcardarella** [comment]
@rushikeshpandit I believe this is now fixed on `main`. Please let me know if you see it again and I'll re-open
