### ISSUE TITLE
[Bug]: Swift BuiltinRegistryGenerator error

### ISSUE THREAD

**Issue by cmnstmntmn** [liveview-native/liveview-client-swiftui#1400]
### What happened?

While trying to build after following the steps from [this gist](https://gist.github.com/bcardarella/4c7079b83240d4129e5260eab0d1ce47)  i got this error:

<img width="1512" alt="Screenshot 2024-08-01 at 23 37 38" src="https://github.com/user-attachments/assets/50f611f2-2b18-4085-9e68-776277243c46">

### Library Version

latest main

### Xcode Version

 16.0 beta 3

### Swift Version

swiftlang-6.0.0.5.15 clang-1600.0.22.6

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

arm64-apple-macosx15.0

### Relevant log output

```shell
/Users/cmnstmntmn/Library/Developer/Xcode/DerivedData/LiveViewStudio-biyunigkwfwcepgmowcxqteespbf/SourcePackages/checkouts/liveview-client-swiftui/Sources/BuiltinRegistryGenerator/BuiltinRegistryGenerator.swift:135:17 The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
```

**Comment by bcardarella** [comment]
Can you check your packages to see if you're pinned on v0.3.0-rc.1?

If you tried the new setup process the generated project for xcode hasn't been updated yet, I'm pushing that in about an hour

**Comment by bcardarella** [comment]
If you are pinned to `v0.3.0-rc.1` you can just change to `branch` : `main` in the pakage dependency manager. Then you'll need to do File/Package Reset to get the new packages. If you are still having.

The other bug you may run into is that the current generated project need to change this LOC https://github.com/liveview-native/liveview-client-swiftui/blob/main/priv/templates/lvn.swiftui.gen/xcodegen/TemplateApp/ContentView.swift#L18

to `.liveForm`

**Comment by cmnstmntmn** [comment]
thank you @bcardarella I'm going to close this since is not longer valid.
