### ISSUE TITLE
Swift / SwiftUI type hex docs

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1412]
We want to generate the docmentation for types that we currently have documented in the Swift source but are not currently being extracted or represented in our Hex docs. Example:

https://hexdocs.pm/live_view_native_swiftui/0.3.0-rc.4/lazyhstack.html

If you click on `[PinnedScrollableViews](https://hexdocs.pm/live_view_native_swiftui/0.3.0-rc.4/lazyhstack.html#PinnedScrollableViews/1)`

It doesn't link out and it should link to these docs: https://github.com/liveview-native/liveview-client-swiftui/blob/63dcf4124276243bbb272f5504a4f019e572a783/Sources/LiveViewNative/Utils/PinnedScrollableViews.swift#L11-L44

**Comment by carson-katri** [comment]
We should probably restructure these documents into top-level sections to match the modifiers:

- Views
- Modifiers
- Types

Each category would be one long page for that specific data type, like the modifier index is currently. Then you can expand the section in the sidebar for links to each one.

It would be ideal if ex_doc has a way of creating custom sidebar categories, or even tabs at the top alongside "Pages", "Modules", and "Mix Tasks". Then each View/Modifier/Type can have its own page. That would speed up page load times and probably help with search.

**Comment by bcardarella** [comment]
Closed in #1440
