### ISSUE TITLE
AttributeReference.swift doesn't run on tvOS has an error 'DragGesture' is unavailable on tvOS'

### ISSUE THREAD

**Issue by dbii** [liveview-native/liveview-client-swiftui#1419]
the relevant line is here. I think it needs a #if line for tvOS.
https://github.com/liveview-native/liveview-client-swiftui/blob/33c62a55ff028972453343250fc345726fe0a2f0/Sources/LiveViewNative/Stylesheets/AttributeReference.swift#L90

**Comment by Fudoshiki** [comment]
same issue

**Comment by bcardarella** [comment]
we should probably expand CI for all device simulators to catch these

**Comment by carson-katri** [comment]
tvOS is already one of our checks, I wonder if it's configured wrong.

**Comment by carson-katri** [comment]
https://github.com/liveview-native/liveview-client-swiftui/blob/33c62a55ff028972453343250fc345726fe0a2f0/.github/workflows/ci.yml#L59

**Comment by bcardarella** [comment]
Fixed in #1422
