### ISSUE TITLE
Wrong text description with "ScrollView With VStack"

### ISSUE THREAD

**Issue by dbii** [liveview-native/liveview-client-swiftui#1427]
https://hexdocs.pm/live_view_native_swiftui/swiftui-views.html#scrollview-with-vstack

ScrollView with VStack says:

"Here's an example using a ScrollView and a HStack to create scrollable text arranged horizontally."

It should say VStack and not say the text is arranged horizontally (maybe should say vertically?).

**Comment by BrooklinJazz** [comment]
Thanks for catching this and making a PR.

**Comment by cmnstmntmn** [comment]
@dbii , @BrooklinJazz you may close this issue.
