### ISSUE TITLE
[Bug]: Styles declared as a separate sheets are not being reloaded due to wrong reload pattern defined

### ISSUE THREAD

**Issue by cmnstmntmn** [liveview-native/liveview-client-swiftui#1429]
### What happened?

Having these relevant code snippets:

**root layout where the styles are impoted**
```html
// hello_web/components/layouts_swiftui/root.swiftui.neex

<.csrf_token />
<Style url={~p"/assets/app.swiftui.styles"} />
<NavigationStack>
  <%= @inner_content %>
</NavigationStack>
```

**home live module**

```html
// hello_web/live/home_live.swiftui.ex

defmodule HelloWeb.HomeLive.SwiftUI do
  use HelloNative, [:render_component, format: :swiftui]
end
```

**template file**

```html
// hello_web/live/swiftui/home_live.swiftui.neex

<Text class="large-title">Large Title Text!</Text>
```

**actual sheet file/class**

```html
//hello_web/styles/app.swiftui.ex

defmodule HelloWeb.Styles.App.SwiftUI do
  use LiveViewNative.Stylesheet, :swiftui

  ~SHEET"""
    "large-title" do
      font(.largeTitle)
    end
  """
end
```

**endpoint live_reload patterns**
```ex
# Watch static and templates for browser reloading.
config :hello, HelloWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/hello_web/(controllers|live|components)/.*(ex|heex)$",
      ~r"lib/hello_web/(live|components)/.*neex$",
      ~r"lib/hello_web/styles/*.ex$",
      ~r"priv/static/*.styles$"
    ]
  ]
```

The simulator is not getting reloaded, closing/reopening the app or resaving the view is needed for the class/style to be applied.

### Library Version

0.3.0

### Xcode Version

16.0 beta 3

### Swift Version

6.0

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

18.0

**Comment by cmnstmntmn** [comment]
Right, instead of having this pattern:

```
`~r"lib/hello_web/styles/*.ex$"`
```

We need to have
```~r"lib/hello_web/styles/.*ex$"```

**Comment by bcardarella** [comment]
if you'd like to PR this the relevant LOC is: https://github.com/liveview-native/live_view_native_stylesheet/blob/main/lib/mix/tasks/lvn.stylesheet.setup.config.ex#L75

**Comment by cmnstmntmn** [comment]
Yeap, already raised this https://github.com/liveview-native/live_view_native_stylesheet/pull/83 with the fix.

**Comment by cmnstmntmn** [comment]
Fixed by https://github.com/liveview-native/live_view_native_stylesheet/pull/83
