### ISSUE TITLE
Wrong attribute case for system images in SwiftUI Views guide

### ISSUE THREAD

**Issue by egutter** [liveview-native/liveview-client-swiftui#1436]
https://hexdocs.pm/live_view_native_swiftui/swiftui-views.html#system-images

Replace system image attributes using kebab case `system-image` or `system-name` to camel case: `systemImage` or `systemName`

**Comment by bcardarella** [comment]
Hi did you want to PR this fix?

**Comment by bcardarella** [comment]
Closed by #1437
