### ISSUE TITLE
[Bug]: Toggle isOn not working

### ISSUE THREAD

**Issue by andr-ec** [liveview-native/liveview-client-swiftui#1438]
### What happened?

The toggle is not showing the correct state.

```
  <Toggle isOn={true} >
  Should be on
  </Toggle>
```
![IMG_203F238F319A-1](https://github.com/user-attachments/assets/b430ba88-69b1-4a0b-8bcb-2f63ed00a08b)

### Library Version

0.3.0

### Xcode Version

lvn go

### Swift Version

lvn go

### On which device or simulator are you running into the problem?

iPhone

### Target Device Operating System Version

17.6.1

**Comment by cmnstmntmn** [comment]
@andr-ec all form components mush be wrapped inside a `LiveForm` component
and also a `name` prop needs to be provided.

```heex
<LiveForm id="some-id" phx-change="form-update" phx-submit="submit">
  <Toggle isOn={true}  name="requiredPropName">
      Should be on
  </Toggle>
</LiveForm>
```

**Comment by bcardarella** [comment]
Closing as @cmnstmntmn's reply was correct

**Comment by bcardarella** [comment]
I'm re-opening this as I believe I closed this in error.

While @cmnstmntmn's comment does fix the issue I believe we are not in alignment with LiveView's HTML equivalent. For example:

```heex
def render(assigns) do
  ~H"""
  <input type="checkbox" checked={true} />
  """
end
```

will render a checkbox with its state set to `true`:

<img width="868" alt="Screenshot 2024-09-29 at 1 55 18 PM" src="https://github.com/user-attachments/assets/fb7c3214-365b-48db-919b-c5fafcdb80d5">

LiveView permits the state attributes to be set and updated from the server without wrapping in a form. What isn't permitted is `phx-submit` and `phx-change` events triggering from an `input` when that `input` is not wrapped by a LV controlled `form`

**Comment by avdept** [comment]
> I'm re-opening this as I believe I closed this in error.
> 
> 
> 
> While @cmnstmntmn's comment does fix the issue I believe we are not in alignment with LiveView's HTML equivalent. For example:
> 
> 
> 
> ```heex
> 
> def render(assigns) do
> 
>   ~H"""
> 
>   <input type="checkbox" checked={true} />
> 
>   """
> 
> end
> 
> ```
> 
> 
> 
> will render a checkbox with its state set to `true`:
> 
> 
> 
> <img width="868" alt="Screenshot 2024-09-29 at 1 55 18 PM" src="https://github.com/user-attachments/assets/fb7c3214-365b-48db-919b-c5fafcdb80d5">
> 
> 
> 
> LiveView permits the state attributes to be set and updated from the server without wrapping in a form. What isn't permitted is `phx-submit` and `phx-change` events triggering from an `input` when that `input` is not wrapped by a LV controlled `form`

Thanks for taking a look at this. I think that controls should not be tied to forms, glad I came across it today
