### ISSUE TITLE
Form fields replace "+" with a space when sent as params

### ISSUE THREAD

**Issue by jtormey** [liveview-native/liveview-client-swiftui#1447]
I noticed this when trying to create a new user account using `+` in an email:

<img width="390" alt="Screenshot 2024-07-24 at 5 04 01 PM" src="https://github.com/user-attachments/assets/fa708a38-2e3f-449e-8e2d-0104b9d79b7f">

Server log with params received:

```elixir
[debug] HANDLE EVENT "validate" in LaxWeb.UserRegistrationLive
  Parameters: %{"_target" => ["user", "email"], "user" => %{"email" => "email trailing@gmail.com"}}
```

**Comment by bcardarella** [comment]
Moved to swiftui client
