### ISSUE TITLE
Support link replace

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1489]

**Comment by carson-katri** [comment]
I think this could be a separate attribute on `NavigationLink`. This is not a feature in SwiftUI, so we would be deviating a bit here:

```heex
<NavigationLink replace={~p"/new-route"}>
  Click me
</NavigationLink>
```

**Comment by bcardarella** [comment]
I wonder if we can introduce a new attr here. Something like `phx-replace` which upgrades the intent that way we can not deviate on the actual SwiftUI API
