### ISSUE TITLE
Parsing error if stylesheet url is wrong

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#1494]
I had a misspelling in the asset url:

`<Style url="/assets/app.swiftu.styles"></Style>`

instead of "swiftui"

and this resulted in the client erroring:

![image](https://github.com/user-attachments/assets/b0718550-1cc8-4271-a4de-8f2b59473b50)

**Comment by carson-katri** [comment]
Does this work:
![Simulator Screenshot - iPhone 16 Pro - 2024-12-13 at 14 46 02](https://github.com/user-attachments/assets/864e9862-c395-4d96-a76b-abd4b73ead72)
