### ISSUE TITLE
[Feature Request] Section isExpanded support

### ISSUE THREAD

**Issue by Serabe** [liveview-native/liveview-client-swiftui#1496]
@bcardarella has more thoughts on how to support this.

**Comment by bcardarella** [comment]
I thinking that the `isExpanded` should be triggered via a client-side event. So perhaps with the LVN commands that we have coming soon.

**Comment by carson-katri** [comment]
We just need a `@ChangeTracked` property for this like we have for all other binding values.

```heex
<Section isExpanded={@is_expanded} phx-change="expansion_changed">
  ...
</Section>
```

**Comment by bcardarella** [comment]
@carson-katri my concern with this being a LV state update is that it won't be as performant. Any latency will break the native feel. Also, a section expansion doesn't seem like something we need to track server side

**Comment by carson-katri** [comment]
It'd work the same as other change tracked values, where it applies client-side immediately, then if the server does update the value to something else after it will apply that. So if you just do:

```heex
<Section isExpanded="false">
  ...
</Section>
```

It will set the default to false, but the user can still open/close it so long as the server doesn't change the `isExpanded` state to a new value.

https://github.com/user-attachments/assets/70106a7e-070c-4519-9979-9c5b749a2378

**Comment by carson-katri** [comment]
And here you can see updating the expansion state from an external button.

https://github.com/user-attachments/assets/5804fde0-3e20-43d2-b395-50d21752cfb0
