### ISSUE TITLE
[RFC] Nested View modifier syntax

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-swiftui#170]
There is an open question around how best to support nested modifiers, which are very common in SwiftUI. Take the [`background(alignment:content:)`](https://developer.apple.com/documentation/swiftui/view/background(alignment:content:)) modifier for example:

```swift
Text("Hello, world!")
  .background(alignment: .center) {
    Text("This is in the background!")
  }
```

Unlike other modifiers, it takes more `View`s as one of the arguments. Here are a few possibilities for supporting this:

## Content IDs
By passing an ID string to a modifier function, we can reference the labelled content within the View. This would likely only require changes on the `liveview-client-swiftui` side.

```html
<text modifiers={@native |> background(alignment: :center, content: "my-background-content")}>
    Hello, world!
    <background:my-background-content>
        <text>This text is in the background!</text>
    </background:my-background-content>
</text>
```

The namespace maps to the modifier name, and the tag name maps to the ID passed to the modifier.

This feels analogous to this SwiftUI pattern of separating out the modifier content:

```swift
var body: some View {
  Text("Hello, world!")
    .background { myBackgroundContent }
}

@ViewBuilder
var myBackgroundContent: some View {
  Text("This text is in the background!")
}
```

### Benefits
* Simple implementation
* Keeps the content of the modifier close to the View it modifies

### Drawbacks
* New users may confuse the string as a text argument to the background, and not notice the nested content.
  * This can be mitigated by using a custom type, and possibly a sigil to construct it: `background(content: Modifier.reference("my-background-content"))`, `background(content: ~R"my-background-content")`

## Template References
A template filename could be passed instead of an ID to content in the same template.

```html
<text modifiers={@native |> background(alignment: :center, content: "my-background-content.heex")}>
    Hello, world!
</text>

<!-- my-background-content.heex -->
<text>This text is in the background!</text>
```

This feels more analogous to having a separate `View` as the content:
```swift
Text("Hello, world!")
  .background { MyBackgroundContent() }

// MyBackgroundContent.swift
struct MyBackgroundContent: View {
  var body: some View {
    Text("This text is in the background!")
  }
}
```

### Benefits
* Allows modifiers to be split up more freely
* The string argument clearly represents a file

### Drawbacks
* Leads to many files quickly
* Likely requires backend changes to support loading the referenced template somewhere, perhaps mounting another LiveView to draw it

## Inline `~H`
Using the sigil, more template code could be passed into the modifier.

```html
<text modifiers={@native |> background(alignment: :center, content: ~H"<text>This text is in the background!</text>")}>
    Hello, world!
</text>
```

### Benefits
* Matches SwiftUI very closely
* Concise

### Drawbacks
* Requires substantial changes to LiveView's engine to support

**Comment by carson-katri** [comment]
The ID method is similar to how SVG [`<defs>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/defs) works, something similar to that could also be possible.

```html
<text modifiers={@native |> background(alignment: :center, content: "#my-background-content")}>
  Hello, world!
  <defs>
    <text id="my-background-content">This text is in the background!</text>
  </defs>
</text>
```

The `<defs>` might be able to go outside the element, if that's more desirable. Although this could lead to a more complex implementation on the client side.

```html
<text modifiers={@native |> background(alignment: :center, content: "#my-background-content")}>
  Hello, world!
</text>
<defs>
  <text id="my-background-content">This text is in the background!</text>
</defs>
```

**Comment by bcardarella** [comment]
Using the id syntax is interesting. If memory serves I think `<defs>` is for deferred content so that naming wouldn't make sense in this context. Would views that are in the modifier tree only be applied to `content` or is it arbitrary?

**Comment by carson-katri** [comment]
If you mean, would the modifier's argument always be called `content`, no. In fact, some modifiers may take multiple children, such as the [`alert(_:isPresented:actions:message:)`](https://developer.apple.com/documentation/swiftui/view/alert(_:ispresented:actions:message:)-3rabc) modifier, which has an `actions` and `message` argument:
```swift
LoginForm(didFail: $didFail)
    .alert(
        alertTitle,
        isPresented: $didFail
    ) {
        Button("OK") {
            // Handle the acknowledgement.
        }
    } message: {
        Text("Please check your credentials and try again.")
    }
```
