### ISSUE TITLE
Custom Xcode Project Template for LVN

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#179]
We should provide a template for creating new LiveView Native projects in XCode.

Even though mixing LiveView into a SwiftUI app is easy providing the project template will give us an opportunity to control how projects should be organized and make it one step easier.

Exposing the registry should be part of the template as well.

**Comment by carson-katri** [comment]
There are a few different ways app project templates could be done.

* Custom Xcode template
* A GitHub [template repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)
* [XcodeGen](https://github.com/yonaskolb/XcodeGen), [Tuist](https://github.com/tuist/tuist), or another similar tool

**Comment by bcardarella** [comment]
I was not aware of the GH template repository. Is that something that can then be linked against in XCode when creating a new project or is it meant for a shallow clone then just opening within XCode?

**Comment by carson-katri** [comment]
No, it just lets you create a new GitHub repository by copying the files from the template.
