### ISSUE TITLE
Thermostat application with LVN > Add missing modifiers

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#183]
Modifiers for Thermostat app:
@supernintendo please use that link https://github.com/chrismccord/phoenix_live_view_example/blob/master/lib/demo_web/live/thermostat_live.ex
* [`Color.gradient`](https://developer.apple.com/documentation/swiftui/color/gradient)
 * [`fontWeight(_:)`](https://developer.apple.com/documentation/swiftui/view/fontweight(_:))
 * [`foregroundStyle(_:)`](https://developer.apple.com/documentation/swiftui/view/foregroundstyle(_:))
 * [`background(_:in:)`](https://developer.apple.com/documentation/swiftui/view/background(_:in:fillstyle:)-20tq5)
 * [`bold()`](https://developer.apple.com/documentation/swiftui/view/bold(_:))
 * [`aspectRatio(_:contentMode:)`](https://developer.apple.com/documentation/swiftui/view/aspectratio(_:contentmode:)-6j7xz)

**Comment by supernintendo** [comment]
- [ ] `Color.gradient`
- [ ] `fontWeight(_:)` - https://github.com/liveviewnative/liveview-client-swiftui/pull/202
- [ ] `foregroundStyle(_:)`
- [ ] `background(_:in:)`
- [ ] `bold()`
- [ ] `aspectRatio(_:contentMode:)`

**Comment by AZholtkevych** [comment]
Waiting for front-end part
