### ISSUE TITLE
SwiftUI scenes

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#189]
We have to decide, whether would we use scenes for LiveViewNative or not
List:

https://developer.apple.com/documentation/swiftui/menubarextra
https://developer.apple.com/documentation/swiftui/settings
https://developer.apple.com/documentation/swiftui/wknotificationscene
https://developer.apple.com/documentation/swiftui/windowgroup
https://developer.apple.com/documentation/swiftui/window
https://developer.apple.com/documentation/swiftui/windowresizability
https://developer.apple.com/documentation/swiftui/documentgroup

**Comment by carson-katri** [comment]
Scenes could be represented as elements:
```html
<window-group>
  ...
</window-group>
<settings>
  ...
</settings>
```
then the Swift package would provide a `LiveScene` or similar struct that creates those.

A simpler approach would be to direct users to use multiple `LiveView` Views within the scenes, since scenes are mostly static anyways:
```swift
WindowGroup {
  LiveView(session: mainSession)
}
Settings {
  LiveView(session: settingsSession)
}
```

**Comment by shadowfacts** [comment]
I don't think we can support scenes at the moment. [SceneBuilder](https://developer.apple.com/documentation/swiftui/scenebuilder) doesn't allow conditionals, so there's no way of handling whatever arbitrary elements are provided by the backend.
