### ISSUE TITLE
SwiftUI -> Lists: OutlineGroup

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#205]
Doc: https://developer.apple.com/documentation/swiftui/outlinegroup

**Comment by carson-katri** [comment]
I'm not sure how to go about implementing this View. `OutlineGroup` requires a `KeyPath` for the `children` property of a type, but this doesn't have a clear mapping to Elixir. For now, I think its use case can be covered by `DisclosureGroup`, and the user could create a custom component on the Elixir side to do the recursion.

**Comment by AZholtkevych** [comment]
Rejecting , according to @carson-katri we won't support this
