### ISSUE TITLE
Styles in the `CustomRegistry`

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-swiftui#245]
It's likely users will want to use their own `ButtonStyle`, `LabelStyle`, etc. in their app. Currently, only the built-in styles can be used. However, this could be expanded to support arbitrary styles from a `CustomRegistry`:

```swift
struct MyAppRegistry: CustomRegistry {
  static func applyButtonStyle(_ style: StyleName, to view: some View) -> some View {
    switch style {
    case .myButtonStyle: view.buttonStyle(MyButtonStyle())
    }
  }

  // Alternatively, an API that returns a `ButtonStyle`.
  static func buttonStyle(_ style: StyleName) -> some ButtonStyle {
    switch style {
    case .myButtonStyle: MyButtonStyle()
    }
  }
}
```
Then the custom style can be used in the markup:
```html
<button button-style="my-button-style">
  Click Me
</button>
```

This is particularly useful for Views that provide little control over their presentation with the built-in styles, such as `DisclosureGroup`.

Alternatively, we could provide some way for styles to be created on the backend.

**Comment by AZholtkevych** [comment]
rejecting according to the team
