### ISSUE TITLE
Modifier -> SwiftUI -> App extensions: widgetAccentable(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#294]
Doc: https://developer.apple.com/documentation/swiftui/view/widgetaccentable(_:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
Widgets cannot be created with LiveView Native.

**Comment by AZholtkevych** [comment]
We won't support this one for now
