### ISSUE TITLE
Modifier -> SwiftUI -> App extensions: widgetLabel(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#295]
Doc:
https://developer.apple.com/documentation/swiftui/view/widgetlabel(_:)-7wguh

- [ ] Swift implementation
- [ ] Elixir implementation

https://developer.apple.com/documentation/swiftui/view/widgetlabel(_:)-8m5o1

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
Widgets cannot be created with LiveView Native.

**Comment by AZholtkevych** [comment]
We won't support this one for now
