### ISSUE TITLE
Modifier -> SwiftUI -> App extensions: widgetLabel(label:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#296]
Doc: https://developer.apple.com/documentation/swiftui/view/widgetlabel(label:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
Widgets cannot be created with LiveView Native.

**Comment by AZholtkevych** [comment]
We won't support this one for now
