### ISSUE TITLE
Modifier -> SwiftUI -> App extension: dynamicIsland(verticalPlacement:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#297]
Doc: https://developer.apple.com/documentation/swiftui/view/dynamicisland(verticalplacement:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
Live Activities cannot be created with LiveView Native.

**Comment by AZholtkevych** [comment]
We won't support this one for now
