### ISSUE TITLE
Chat App Architecture

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#3]
Real-time chat application

There should be rooms that correspond to the schedule of events at ElixirConf. So if it is a matter of scraping the schedule or just having general rooms that correspond to the tracks themselves is OK

When a user installs the app they’ll be prompted with their email address. Once this is submitted an email will be sent to that address if it is on the list of attendees. Either a magic link or a passcode for authentication will be provided. First name and last name will be pre-seeded associated with the attendee’s email address. This allows users to (mostly) confirm their identity. We don’t want anonymous users on this app.

Users should have the option to silence any one specific user. Silencing a user also means you cannot see them in the list of other users and they cannot see you. This is a permanent selection and cannot be undone.

The backoffice admin side of this should have a way to load in all users. So there needs to be an admin authentication function then essentially a way to upload probably a CSV of:

`email,first_name,last_name`

When logged into the app you should be in the “lobby” and have a list of the different room tracks.

Selecting a track brings you to the chat room for that track where the real-time conversation is happening. You should be able to see the entire chat history of the room.

There is no concept of DMs in this app. Only rooms-specific conversation

We are working off of the full names, no usernames. So when in a room you would see a list of everyone in the room. Names are sorted alphabetically `last_name, first_name`

**Comment by AZholtkevych** [comment]
Ask Brian

**Comment by AZholtkevych** [comment]
Done for the Elixir conference by @shadowfacts
