### ISSUE TITLE
[idea] [ios] Translatable String Component

### ISSUE THREAD

**Issue by clsource** [liveview-native/liveview-client-swiftui#33]
# Why?
For easier translation of strings. Currently there are awesome translation solution for Phoenix
and this component may not be needed.

But there are lot of apps that have `Localizable.strings` file that would benefit for using the Device Translation tools instead
of the server translation tools.

## How

Example Syntax For a Single String

```xml
<trans fallback="Key Not Found" table="" bundle="">
  My Translatable String Key
</trans>
```

Example Syntax for Inside another component

```xml
<button><trans>My Translatable Button</trans></button>
```

Example as a global. All strings would be translated

```xml
<trans :all>
<myComponent title="My Title"></mycomponent>
</trans>
``` 

This is an Objective-C with a sample way of doing this:

```objective-c
/*
Mappings to the
`localizedStringForKey:value:table:`

https://developer.apple.com/documentation/foundation/nsbundle/1417694-localizedstringforkey

Returns a localized version of the string designated by the specified key and residing in the specified table.

- If table is null, it will use the file named Localizable.strings
- Bundle is the bundle identifier string. If bundle is null, it will use [NSBundle mainBundle]
- value is the default value if the key is not found.
*/

NSString *key = [params string:@"key" default:@""];
NSString *value = [params string:@"value" default:@""];
NSString *table = [params string:@"table"];
NSString *bundleIdentifier = [params string:@"bundle"];

NSBundle *bundle = [NSBundle mainBundle];

if (bundleIdentifier) {
    bundle = [NSBundle bundleWithIdentifier:bundleIdentifier];

    if (!bundle) {
        bundle = [NSBundle mainBundle];
    }
}

return [bundle localizedStringForKey:key value:value table:table];
```

**Comment by shadowfacts** [comment]
Supporting client-side translation is a good idea. The less data that needs to be sent from the client to the backend in order to render, the better. This will probably be part of the `<text>` element, to align with how SwiftUI uses the `Text` view. e.g., `<text localization-key="My Title" />`

**Comment by BryanJBryce** [comment]
@shadowfacts Yeah, just the key would be enough as long as the app has the translations file. I wonder if there's a way to download a `.strings` file on mount though, that might be pretty cool, but not required at first.

**Comment by bcardarella** [comment]
What is the advantage to doing this on device and not relying on i18n from server-side?
