### ISSUE TITLE
Documentation: SwiftUI -> Layout Containers -> Presentation containers: NavigationStack

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#395]
As a PO I'd like to have documentation for the [NavigationStack](https://github.com/liveviewnative/liveview-client-swiftui/issues/122)

**Comment by AZholtkevych** [comment]
@carson-katri is there any PR to link? Thank a lot

**Comment by carson-katri** [comment]
There isn't, this functionality was already documented.
