### ISSUE TITLE
Documentation: SwiftUI -> Layout Containers -> Presentation containers: NavigationSplitView

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#396]
As a PO I'd like to have documentation for the [NavigationSplitView](https://github.com/liveviewnative/liveview-client-swiftui/issues/123)

**Comment by AZholtkevych** [comment]
@carson-katri is there any PR to link? Thank a lot

**Comment by carson-katri** [comment]
This functionality was already documented in c9bfce9
