### ISSUE TITLE
Documentation: SwiftUI -> Layout Containers -> Presentation containers: TabView

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#397]
As a PO I'd like to have documentation for the [TabView](https://github.com/liveviewnative/liveview-client-swiftui/issues/125)

**Comment by AZholtkevych** [comment]
@carson-katri is there any PR to link? Thank a lot

**Comment by carson-katri** [comment]
This functionality was already documented in da4772a
