### ISSUE TITLE
Modifier -> SwiftUI -> Navigation: navigationTitle(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#407]
Doc:
https://developer.apple.com/documentation/swiftui/view/navigationtitle(_:)-43srq

- [ ] Swift implementation
- [ ] Elixir implementation

https://developer.apple.com/documentation/swiftui/view/navigationtitle(_:)-5di1u

- [ ] Swift implementation
- [ ] Elixir implementation

https://developer.apple.com/documentation/swiftui/view/navigationtitle(_:)-avgj

- [ ] Swift implementation
- [ ] Elixir implementation

https://developer.apple.com/documentation/swiftui/view/navigationtitle(_:)-6jofs

- [ ] Swift implementation
- [ ] Elixir implementation

https://developer.apple.com/documentation/swiftui/view/navigationtitle(_:)-7onr8

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
This modifier is already implemented.
