### ISSUE TITLE
Modifier -> SwiftUI -> Navigation: tabItem(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#417]
Doc: https://developer.apple.com/documentation/swiftui/view/tabitem(_:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by AZholtkevych** [comment]
According to the @carson-katri @shadowfacts we won't support this

**Comment by AZholtkevych** [comment]
https://liveview-native.github.io/liveview-client-swiftui/documentation/liveviewnative/livesessionconfiguration/navigationmode-swift.enum/tabview(tabs:)

**Comment by carson-katri** [comment]
This will need to be supported along with the `page` style `TabView`.
