### ISSUE TITLE
Modifier -> SwiftUI -> Navigation: navigationSplitViewStyle(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#483]
Doc: https://developer.apple.com/documentation/swiftui/navigationSplitViewStyle

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by AZholtkevych** [comment]
@dginsburg could you please clarify why it is blocked? Thanks a lot

**Comment by AZholtkevych** [comment]
@dginsburg sure

**Comment by AZholtkevych** [comment]
Blocked by Core part

**Comment by AZholtkevych** [comment]
Unblocked right now since https://github.com/liveview-native/phoenix-channels-client/issues/15 has been done
FYI @carson-katri @KronicDeth @Bajix 
@carson-katri you can proceed with that

**Comment by carson-katri** [comment]
This is still blocked. `phoenix-channels-client` still needs to be integrated into this package.

**Comment by AZholtkevych** [comment]
According to @carson-katri it is autogenerated. Closing
