### ISSUE TITLE
Repo changes

### ISSUE THREAD

**Issue by bcardarella** [liveview-native/liveview-client-swiftui#59]
I'd like to start imposing some project constraints. The following changes need to be made on the Core branch:

* https://github.com/liveviewnative/liveview-client-swiftui/tree/core/Sources/PhoenixLiveViewNative directory should be renamed to `LiveView-Native/`
* All of the views are prepended with `Phx`. This needs to be done away with, for example: https://github.com/liveviewnative/liveview-client-swiftui/blob/core/Sources/PhoenixLiveViewNative/Views/PhxHStack.swift should be renamed to `HStack.swift` and the corresponding struct needs to be named `HStack` as well under the implied namespace of the library. We can reference the original SwiftUI view: https://github.com/liveviewnative/liveview-client-swiftui/blob/core/Sources/PhoenixLiveViewNative/Views/PhxHStack.swift#L19 with `SwiftUI.HStack`
* We need to start seeing tests. Currently the test suite is still primarily made up of the original tests that I wrote over two years ago.

**Comment by AZholtkevych** [comment]
Ask Brian, is it done or not? Can we close it?
