### ISSUE TITLE
Modifier -> SwiftUI -> View fundamentals: onAppear(perform:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#608]
Doc: https://developer.apple.com/documentation/swiftui/view/onappear(perform:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by AZholtkevych** [comment]
It should be more investigated

**Comment by shadowfacts** [comment]
I started investigating this and #609 (see 33f5eb4e03f54202054e3a736d1792644074b814) but ran into an issue: every time an element appears or disappears, _both_ the onAppear and onDisappear callbacks fire. It's not immediately clear to me why, but I suspect it has to do with the notion of element identity not being preserved across view updates (see liveview-native/liveview-native-core#13).

**Comment by dginsburg** [comment]
@AZholtkevych I don't think this is a good ticket for me to work on. If Anil didn't know how to do it then I definitely won't. It involves parts of the architecture I don't know at all.

**Comment by carson-katri** [comment]
I wasn't able to replicate the mentioned issue in a few simple tests, perhaps it shows up with more complex hierarchies. I've opened a PR with @shadowfacts implementation: #970

**Comment by AZholtkevych** [comment]
@carson-katri could you please link PR here

**Comment by AZholtkevych** [comment]
@carson-katri please merge this one
