### ISSUE TITLE
Modifier -> SwiftUI -> View fundamentals: onDisappear(perform:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#609]
Doc: https://developer.apple.com/documentation/swiftui/view/ondisappear(perform:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by AZholtkevych** [comment]
depends on #608

**Comment by dginsburg** [comment]
@AZholtkevych Same as #608 regarding my (lack of) knowledge to complete this one.

**Comment by AZholtkevych** [comment]
@carson-katri could you please link PR here

**Comment by AZholtkevych** [comment]
@carson-katri could you please merge this one
