### ISSUE TITLE
Modifier -> SwiftUI -> Documents: renameAction(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#613]
Doc:
https://developer.apple.com/documentation/swiftui/view/renameaction(_:)-6lghl

- [x] Swift implementation
- [x] Elixir implementation

https://developer.apple.com/documentation/swiftui/view/renameaction(_:)-324yw

- [x] Swift implementation
- [x] Elixir implementation

**Comment by carson-katri** [comment]
Implemented in #326
