### ISSUE TITLE
Modifier -> SwiftUI -> View fundamentals -> View -> Input and event modifiers: shortcutsLinkStyle(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#626]
Doc: https://developer.apple.com/documentation/swiftui/view/shortcutslinkstyle(_:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
LiveView Native does not have the ShortcutsLink view, so this does not apply.
