### ISSUE TITLE
Modifier -> SwiftUI -> View fundamentals -> View -> Input and events modifiers: siriTipViewStyle(_:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#627]
Doc: https://developer.apple.com/documentation/swiftui/view/siritipviewstyle(_:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by carson-katri** [comment]
LiveView Native does not have the SiriTipView, so this does not apply.
