### ISSUE TITLE
Modifier -> SwiftUI -> Technology-specific views: photosPicker(isPresented:selection:matching:preferredItemEncoding:)

### ISSUE THREAD

**Issue by AZholtkevych** [liveview-native/liveview-client-swiftui#680]
Doc: https://developer.apple.com/documentation/swiftui/view/photospicker(ispresented:selection:matching:preferreditemencoding:)

- [ ] Swift implementation
- [ ] Elixir implementation

**Comment by AZholtkevych** [comment]
Blocked by file uploading

**Comment by AZholtkevych** [comment]
Blocked by https://github.com/liveview-native/liveview-native-core/issues/15

**Comment by bcardarella** [comment]
This is part of PhotoKit https://developer.apple.com/documentation/photokit
