### ISSUE TITLE
Use a Plugin for the TutorialRepoGenerator

### ISSUE THREAD

**Issue by carson-katri** [liveview-native/liveview-client-swiftui#898]
A limitation was noted in `Package.swift`:

https://github.com/liveview-native/liveview-client-swiftui/blob/0cbc31fec8f72c02205a193195a62f14c9122f73/Package.swift#L97-L98

As of Swift 5.9, this can be done with `allowNetworkConnections(scope:reason:)` or the `--allow-network-connections` flag: https://github.com/apple/swift-package-manager/pull/6114

**Comment by AZholtkevych** [comment]
Rejecting according to the team
